ARGOeu/argo-web-api

- ar-web-api.spec
We need to build latest version before merging devel to master as latest commit on devel branch did not include spec file update (for deploying and testing purposes).
> Test cipher changes

- README.md
This PR fixes and enhances the contents of the README.md file. 
Please review /cc @skanct @themiszamani
> Fixes in README.md file

- app/availabilityProfiles/availabilityProfilesController.go
- app/availabilityProfiles/availabilityProfiles_test.go
- app/factors/factorsController.go
- app/ngiAvailability/ngiAvailabilityController.go
- app/poemProfiles/poemProfilesController.go
- app/recomputations/recomputationsController.go
- app/serviceFlavorAvailability/serviceFlavorAvailabilityController.go
- app/siteAvailability/siteAvailabilityController.go
- app/statusDetail/statusDetailController.go
- app/statusEndpoints/statusEndpointsController.go
- app/statusMsg/statusMsgController.go
- app/statusServices/statusServicesController.go
- app/statusSites/statusSitesController.go
- app/voAvailability/voAvailabilityController.go
- main.go
- utils/authentication/authenticate.go
- utils/authentication/authenticate_test.go
- utils/config/config.go
- utils/mongo/mongoConnect.go
- utils/mongo/mongoQuery.go
- utils/mongo/mongo_test.go
* Added the functions to authenticate clients to tenants and return their database configuration
* Changed all the uses of mongo.OpenSession to use cfg.MongoDB
> ARGO-128 Created utility function and fixes

- app/metricProfiles/metricProfilesController.go
- app/metricProfiles/metricProfilesModel.go
- app/metricProfiles/metricProfilesView.go
- app/metricProfiles/metricProfiles_test.go
- main.go
- utils/mongo/mongoQuery.go
* Renamed PoemProfiles to MetricProfiles
* Added test for the List operation
* Added support for the new schema of metricProfiles
> ARGO-122 mulitenancy support for metric profiles

- app/tenants/tenantsController.go
- app/tenants/tenantsModel.go
- app/tenants/tenantsView.go
- app/tenants/tenants_test.go
- main.go
- utils/mongo/mongoQuery.go
Reopened pull request (see previous one here:https://github.com/ARGOeu/argo-web-api/pull/84) 
Eliminated conflicts in this one, by rebuilding upon changes introduced in PR:https://github.com/ARGOeu/argo-web-api/pull/80
Here is implemented a tenants package (`./app/tenants`) which allows admin users to
- Create new tenants (POST)
- Read information by listing all or specific tenant by name (GET)
- Update existing tenant (PUT)
- Delete existing tenant (DELETE)
All requests are authenticated against a registered admin user by calling func: `./utils/mongo.authenticateAdmin` (introduced in PR:https://github.com/ARGOeu/argo-web-api/pull/80)
_Note_: tenants Model uses the same structures (`Tenant`, `TenantDBConf` and `TenantUser`) both for the mongo bson document interfacing and for the xml & …
> ARGO-119 Tenant Information (CRUD)

- app/serviceFlavorAvailability/serviceFlavorAvailabilityController.go
- app/serviceFlavorAvailability/serviceFlavorAvailabilityModel.go
- app/serviceFlavorAvailability/serviceFlavorAvailabilityView.go
- app/serviceFlavorAvailability/serviceFlavorAvailability_test.go
- Added modifications in SF controller function to check for tenant API key
- Added unit tests for the following:
- Check daily SF results
- Check monthly SF results
- Check authorization works
> ARGO-138 Added multi tenant functionality for SF reports and unit tests

- app/statusDetail/statusDetailController.go
- app/statusMsg/statusMsgController.go
- app/statusMsg/statusMsgModel.go
- app/statusMsg/statusMsgView.go
- app/statusMsg/statusMsg_test.go
Add mutitenancy to status metric messages (summary/message)
Add unit tests
> ARGO-134 - Multitenantcy in status metric messages

- README.md
please review /cc @themiszamani
> ARGO-149 Updated readme

- doc/api.md
- doc/api/avail-reliab.md
- doc/api/availabilityprofs.md
- doc/api/metricprofiles.md
- doc/api/recalculationrequests.md
- doc/api/status-results.md
please review /cc @themiszamani
> ARGO-149 Transfer of docs

- app/reports/reportsController.go
- app/reports/reportsModel.go
- app/reports/reportsView.go
- app/reports/reports_test.go
- app/statusDetail/statusDetailController.go
- app/statusDetail/statusDetailModel.go
- app/statusDetail/statusDetailView.go
- app/statusDetail/statusDetail_test.go
- app/statusMsg/statusMsgController.go
- app/statusMsg/statusMsgModel.go
- app/statusMsg/statusMsgView.go
- app/statusMsg/statusMsg_test.go
- main.go
refactor job references to reports
change statusMsg reference to reports
change statusDetails references to reports
update unittests
> ARGO-186 refactor jobs module to reports

- app/metric_result/controller.go
- app/metric_result/metric_test.go
- app/metric_result/model.go
- app/metric_result/routing.go
- app/metric_result/view.go
- doc/api/metric-result.md
- routing/routes.go
> ARGO-178 Metric details

- app/results/Controller.go
- app/results/Model.go
- app/results/View.go
- app/results/endpointgroup_test.go
- app/results/routing.go
- app/results/serviceflavor_test.go
- doc/api/results.md
> ARGO-179 Service Flavors A/R/U results

- app/results/Controller.go
- app/results/endpointgroup_test.go
- app/results/routing.go
- app/results/serviceflavor_test.go
- app/results/supergroup_test.go
please review /cc @makistsantekidis @skanct
> ARGO-209 Wrong key should return 401 unauthorized

- app/statusMetrics/controller.go
- app/statusMetrics/model.go
- app/statusMetrics/statusMetrics_test.go
- app/statusMetrics/view.go
- doc/api/status-results.md
> ARGO-213 Status metrics

- app/results/Model.go
- app/results/endpointgroup_test.go
- app/results/routing.go
- app/results/serviceflavor_test.go
- app/results/supergroup_test.go
please review /cc @makistsantekidis @kaggis
> Rename endpoint_group attribute in reports collection.

- app/results/routing.go
- utils/authentication/authenticate.go
- Adding missing defer call to close mongo session
> Mongo open connections fix 

- app/recomputations2/Controller.go
- app/recomputations2/View.go
- app/recomputations2/recomputation_test.go
- app/recomputations2/routing.go
- respond/respond.go
- routing/router.go
- routing/routes.go
Minor fixes for routing, uuid selection in requests and stricter matching rules
> Recomputation fixes

- app/aggregationProfiles/aggregationProfiles_test.go
- app/aggregationProfiles/controller.go
- app/aggregationProfiles/model.go
- app/aggregationProfiles/routing.go
- app/aggregationProfiles/view.go
- doc/v2/docs/aggregation_profiles.md
- routing/routes.go
Implement crud functionality in Aggregation (Availability) Profiles
- based on ARGO-223 (that must be merged first)
> ARGO-224 Aggregation profiles

- app/statusEndpointGroups/routing.go
- app/statusEndpoints/routing.go
- app/statusMetrics/routing.go
- app/statusServices/routing.go
- Added missing defers on group check routines on status results
> Adding Defer Close connections

- app/aggregationProfiles/aggregationProfiles_test.go
- app/metricProfiles/metricProfiles_test.go
- app/operationsProfiles/controller.go
- app/operationsProfiles/model.go
- app/operationsProfiles/operationsProfiles_test.go
- app/operationsProfiles/routing.go
- app/operationsProfiles/view.go
- doc/v2/docs/operations_profiles.md
- respond/respond.go
- routing/routes.go
This PR implements Operations Profiles requests in api v2
> ARGO-225 Operations profiles

- app/aggregationProfiles/aggregationProfiles_test.go
- app/aggregationProfiles/model.go
During validation of metric_profile reference lookup was made on the wrong collection
> Fix bug: aggregation_profiles 

- doc/v2/docs/recomputations.md
please review /cc @makistsantekidis
> Replace Content-Type header with Accept in recomputations document

- argo-web-api.conf
- argo-web-api.spec
- default.conf
- doc/api/installation.md
> ARGO-240 Adds installation document and configuration file for service

- app/metricResult/metric_test.go
- app/reports/reportsModel.go
- app/reports/reports_test.go
- app/results/supergroup_test.go
- app/statusEndpointGroups/statusEndpointGroups_test.go
- app/statusEndpoints/statusEndpoints_test.go
- app/statusMetrics/statusMetrics_test.go
- app/statusServices/statusServices_test.go
please review 
/cc @makistsantekidis
> Change uuid -> id in reports references

- app/reports/reportsController.go
- app/results/Controller.go
- app/results/Model.go
- app/results/endpointgroup_test.go
- app/results/routing.go
- app/results/serviceflavor_test.go
- app/results/supergroup_test.go
- respond/respond.go
Api calls in the results package return incomplete responses according to the api specifications. 
Refactoring along with changes to improve code quality and fix missing parts of responses in the results package.
> [ARGO-218] Fixes in result api responses

- doc/swagger/swagger.yaml
Add swagger yaml definitions for api v2 /reports  CRUD calls
- Add swagger yaml definitions
> ARGO-261 Swagger definitions for reports calls

- doc/swagger/swagger.yaml
Add swagger yaml definition for /api/v2/admin/tenants CRUD calls
> ARGO-260 Swagger definition for tenants

- .travis.yml
We would like to have comprehensive test coverage metrics with Cobertura report format in xml format so that Jenkins or another CI can parse and present them.
Use gocov packages to: 
1. Run all the tests with cover enabled
2. Parse the results into gocov's JSON interchange format.
3. Convert it into the Cobertura xml format and output it into a file for the CI to present
> ARGO-279 Add test coverage metrics

- app/statusEndpointGroups/controller.go
- app/statusEndpointGroups/model.go
- app/statusEndpointGroups/statusEndpointGroups_test.go
- app/statusEndpointGroups/view.go
- app/statusEndpoints/controller.go
- app/statusEndpoints/model.go
- app/statusEndpoints/statusEndpoints_test.go
- app/statusEndpoints/view.go
- app/statusMetrics/controller.go
- app/statusMetrics/model.go
- app/statusMetrics/statusMetrics_test.go
- app/statusMetrics/view.go
- app/statusServices/controller.go
- app/statusServices/model.go
- app/statusServices/statusServices_test.go
- app/statusServices/view.go
- respond/respond.go
- respond/validators.go
Current status requests do not use the latest error responses and marshalling.
Align all the status responses to the current schema
> [ARGO-256] Fixes for status reponses

- doc/swagger/swagger.yaml
Fix a minor tag misplacement in swagger.yaml definition
> ARGO-289 Fix swagger tag misplacement

- doc/swagger/swagger.yaml
This pull request contains the meta-data for the results api calls in the swagger definitions.
> ARGO-259 results swagger definitions

- app/factors/factorsController.go
- app/factors/factorsModel.go
- app/factors/factorsView.go
- app/factors/factors_test.go
- app/factors/routing.go
- doc/swagger/swagger.yaml
- doc/v2/docs/factors.md
- routing/router.go
- routing/routes.go
Factor call is now part of v2 with new routing and router based testing.
> ARGO-284 Factors v2

- .travis.yml
Use mongoDB 3.x during tests in travis
> ARGO-291 use mongodb 3.x in travis

- app/aggregationProfiles/aggregationProfiles_test.go
- app/factors/factors_test.go
- app/metricProfiles/metricProfiles_test.go
- app/operationsProfiles/operationsProfiles_test.go
- app/recomputations2/recomputation_test.go
- app/reports/reports_test.go
- app/results/endpointgroup_test.go
- app/results/serviceflavor_test.go
- app/results/supergroup_test.go
- app/tenants/tenants_test.go
Improve test performance by not deleting the database for each test.
This pull request
```
time go test ./...
real	0m13.839s
user	0m48.096s
sys	0m5.327s
```
Current devel
```
time go test ./...
real	0m38.767s
user	0m44.958s
sys	0m5.116s
```
> ARGO-171 Improve test performance

- argo-web-api.spec
Spec file should be update to use the godep mechanism introduced in ARGO-292 https://github.com/ARGOeu/argo-web-api/pull/185
> ARGO-302 Update Spec file to use godep

- doc/api/installation.md
- doc/v2/docs/aggregation_profiles.md
- doc/v2/docs/index.md
- doc/v2/docs/metric_profiles.md
- doc/v2/docs/operations_profiles.md
- doc/v2/docs/reports.md
- doc/v2/docs/tenants.md
Updated index page 
Changes to all pages (headings and style).
> API v2 changes

- doc/swagger/swagger.yaml
Minor fixes in yaml based ARGO API specification. 
please review /cc @kaggis
> ARGO-300 Minor Fixes in swagger yaml specification of API

- doc/swagger/swagger.yaml
please review /cc @themiszamani
> ARGO-300 Added description in swagger.yml

- .travis.yml
- Godeps/Godeps.json
Fix issue with Travis CI failures.
> ARGO-380 Travis check fix

- doc/swagger/swagger.yaml
> ARGO-392 Add recomputations resource description in swagger spec file

- doc/swagger/swagger.yaml
- doc/v2/docs/metrics.md
- doc/v2/mkdocs.yml
Swagger update metric results. 
Mkdocs add metric results documentation
> [ARGO-439]: Add metric results to mkdocs and swagger

- app/results/Controller.go
Fix Controller's DailySuperGroup method in results package:
- Refactor query in accordance with the MonthlyDailySupergroup method query
> Fix daily supergroup controller method

- app/aggregationProfiles/aggregationProfiles_test.go
- app/factors/factors_test.go
- app/metricProfiles/metricProfiles_test.go
- app/metricResult/metric_test.go
- app/operationsProfiles/operationsProfiles_test.go
- app/recomputations2/recomputation_test.go
- app/reports/reports_test.go
- app/results/endpointgroup_test.go
- app/results/serviceflavor_test.go
- app/statusEndpointGroups/statusEndpointGroups_test.go
- app/statusEndpoints/statusEndpoints_test.go
- app/statusMetrics/statusMetrics_test.go
- app/statusServices/statusServices_test.go
- app/tenants/tenants_test.go
- utils/authentication/authenticate.go
- utils/authentication/authenticate_test.go
- utils/mongo/mongo_test.go
During requests add user access information to log
e.g.
```
2016/11/03 14:27:00 ACCESS	User: JohnDoe
```
> ARGO-606 Add WEB API username to logging

- main.go
- utils/authentication/authenticate.go
- Set log to stdout
- Replace tab with space in access log message
> Set log output to stdout

- app/statusEndpointGroups/view.go
- app/statusEndpoints/view.go
- app/statusMetrics/view.go
- app/statusServices/view.go
- utils/config/config.go
- Fix in config package regarding hbase cfg and zkquorum parameter
- Minor fixes in status_* packages in views regarding 'timestamp' field --> 'ts_monitored'
> ARGO-794 Hbase zkquorum config fix. Hbase query minor fixes

- app/statusEndpointGroups/controller.go
- app/statusEndpoints/controller.go
- app/statusMetrics/controller.go
- app/statusServices/controller.go
- utils/hbase/hbaseQuery.go
- utils/logging/logger.go
Add timeout context to hbase related queries 
Fix hbase error return references in status related controllers
> ARGO-835 Set timeout to hbase related requests

- respond/respond.go
> ARGO-894 Fix error handling for internal server errors

- argo-web-api.service
- argo-web-api.spec
Create argo-web-api.service file 
Update spec to deploy service file
> AO-398 Add argo-web-api systemd service file

- scripts/mongodb/populate_default_roles.js
Add tenant get_status and update_status roles in script that initializes mongodb collection
> ARGO-1433 Add tenant status roles to init db script

- argo-web-api.spec
Remove godep references from argo-web-api.spec
> Remove godep reference from spec

- argo-web-api.spec
- version/version.go
> version bump to 1.8.0

- argo-web-api.spec
Update spec file for release of argo-web-api version 1.8.1
> Spec update for argo-web-api 1.8.1

- app/weights/weights_test.go
Add the ability to argo-web-api to store list of weights used in computations as a resource. Give the ability to have CRUD functionality so the connectors can create update and store new weights lists
> ARGO-2098 Implement weights resource with CRUD functionality

- app/tenants/controller.go
- app/tenants/model.go
- app/tenants/tenants_test.go
- doc/swagger/swagger.yaml
- doc/v2/docs/tenants.md
Add topology feed information needed by components such as connectors to the tenant confiruation body
> ARGO-2161 Add topology feed parameters to tenant configuration

- app/latest/latest_test.go
- app/topology/routing.go
- app/topology/topology_test.go
- doc/swagger/swagger.yaml
- doc/v2/docs/topology.md
Change topology statistics call path from `/api/v2/topology` to `/api/v2/topology/stats`
> ARGO-2183 Change topology stats signature path Topology stats change path

- Jenkinsfile
Environmental Variables are not interpret in Jenkinsfile when we use single quotes
> DEVOPS-66 Fix variables

- Jenkinsfile
Instead of having the script in every jenkinsfile we use the build-rpm.sh script to import it from each jenkinsfile we want
> DEVOPS-54 Build each stage in different container

- Jenkinsfile
Update downstream job path to be able to execute it in new jenkins setup
> DEVOPS-77 New jenkins 

- argo-web-api.spec
- version/version.go
Update version and spec file to 1.9.0
> Version bump to v.1.9.0

- Jenkinsfile
Required post build step to remove any leftover artifact created from previous build
> DEVOPS-111 Add clean workspace post build step

- app/statusEndpoints/routing.go
- app/statusFlatEndpoints/controller.go
- app/statusFlatEndpoints/model.go
- app/statusFlatEndpoints/routing.go
- app/statusFlatEndpoints/statusFlatEndpoints_test.go
- app/statusFlatEndpoints/view.go
- doc/swagger/swagger.yaml
- doc/v2/docs/results.md
- doc/v2/docs/status.md
- routing/routes.go
Provide a flat list of status results for all avaliable service endpoints
>  ARGO-2228 Add flat list for status endpoint results

- app/thresholdsProfiles/controller.go
- app/thresholdsProfiles/thresholdsProfiles_test.go
- Fix issue to check that name is unique when updating a threshold profile
- Update unit tests with relevant scenario
> ARGO-2418 Fix threshold profile update name unique check

- README.md
> update funding info in readme

- argo-web-api.spec
- version/version.go
> bump to version 1.9.1

- postman/argo-web-api_tests.json
Provide postman tests for:
- top level endpoint group a/r results
- top level endpoint group status results
- service a/r results
- service status results
- endpoint a/r results
- endpoint status results
- metric results
- flat list of endpoint a/r results
- flat list of specific metric results by metric type
> ARGO-2503 Provide postman tests for results

- app/statusEndpoints/statusEndpoints_test.go
- app/statusFlatEndpoints/statusFlatEndpoints_test.go
- app/tenants/controller.go
- app/tenants/routing.go
- app/tenants/tenants_test.go
- app/tenants/view.go
- doc/swagger/swagger.yaml
- scripts/mongodb/populate_default_roles.js
- website/docs/tenants.md
Implement a call to update information on an existing user in a tenant by calling
`PUT /api/v2/tenants/{tenant_id}/users/{user_id}`
Implementation
> ARGO-2474 Update user in tenant

- app/statusEndpoints/statusEndpoints_test.go
- app/statusFlatEndpoints/statusFlatEndpoints_test.go
- app/tenants/controller.go
- app/tenants/model.go
- app/tenants/routing.go
- app/tenants/tenants_test.go
- app/tenants/view.go
- doc/swagger/swagger.yaml
- scripts/mongodb/populate_default_roles.js
- website/docs/tenants.md
Implement a call to quickly request a user's api key renewal
`POST /api/v2/tenants/{tenant_id}/users/{user_id}/renew_api_key`
Implementation
> ARGO-2476 Refresh User's token

- app/statusEndpoints/statusEndpoints_test.go
- app/statusFlatEndpoints/statusFlatEndpoints_test.go
- app/tenants/controller.go
- app/tenants/model.go
- app/tenants/routing.go
- app/tenants/tenants_test.go
- app/tenants/view.go
- doc/swagger/swagger.yaml
- scripts/mongodb/populate_default_roles.js
- website/docs/tenants.md
Implement a call to remove existing user in a tenant by calling
`DELETE /api/v2/tenants/{tenant_id}/users/{user_id}`
Implementation
> ARGO-2475 Remove tenant user

- app/statusEndpoints/statusEndpoints_test.go
- app/statusFlatEndpoints/statusFlatEndpoints_test.go
- app/tenants/controller.go
- app/tenants/model.go
- app/tenants/routing.go
- app/tenants/tenants_test.go
- app/tenants/view.go
- doc/swagger/swagger.yaml
- scripts/mongodb/populate_default_roles.js
- website/docs/tenants.md
Implement a call to view a list of available users in each tenant
`GET /api/v2/tenants/{tenant_id}/users`
Implementation
> ARGO-2593 List tenant users

- app/statusEndpoints/statusEndpoints_test.go
- app/statusFlatEndpoints/statusFlatEndpoints_test.go
- app/tenants/controller.go
- app/tenants/model.go
- app/tenants/routing.go
- app/tenants/tenants_test.go
- app/tenants/view.go
- doc/swagger/swagger.yaml
- scripts/mongodb/populate_default_roles.js
- website/docs/tenants.md
Implement a call to view information on a specific user member of a specific tenant
`GET /api/v2/tenants/{tenant_id}/users/{user_id}`
Implementation
> ARGO-2594 Get user information

- Jenkinsfile
- app/tenants/controller.go
- app/tenants/model.go
- app/tenants/routing.go
- app/tenants/tenants_test.go
- app/tenants/view.go
- doc/swagger/swagger.yaml
- scripts/mongodb/populate_default_roles.js
- website/docs/downtimes.md
- website/docs/status.md
- website/docs/tenants.md
- website/docs/topology_groups.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Update to latest docusaurus 2.alpha.063
> ARGO-2599 Update to latest docusaurus

- app/issues/controller.go
- app/issues/issues_test.go
- app/issues/model.go
- app/issues/routing.go
- app/issues/view.go
- doc/swagger/swagger.yaml
- routing/routes.go
- scripts/mongodb/populate_default_roles.js
- website/docs/issues.md
- website/sidebars.js
Give the ability to quickly observe problematic endpoints
Add a new api call under
`/api/v2/issues/{report_name}/endpoints`
to quickly view the latest problematic endpoints
Give tha ability to optionaly filter by status value by adding `&filter=` `critical` or  `warning` or `missing` or `unknown`
> ARGO-2558 Show list of problematic endpoints

- app/weights/controller.go
- Replace panic placeholders with 500 error responses 
- Fix weight name query 
- Fix date stamping in put operation 
- Fix comments
> ARGO-2690 Minor fixes and cleanups in weights resource

- argo-web-api.spec
- version/version.go
> Version 1.9.2

- app/recomputations2/Controller.go
Add omitted mongo close session in recomputation2 handler package
> ARGO-3241 close mongodb sessions in recomputation handlers

- app/downtimes/controller.go
- app/downtimes/downtimes_test.go
Return the downtimes of the exact date requested or else return empty list
> ARGO-3265 Return exact date downtime instead of close to date

- app/metricResult/controller.go
- app/metricResult/model.go
- app/metricResult/view.go
Add an additional urlParameter ?report=report_name when displaying detailed metric results
> ARGO-3458 Serve metric details per report

- main.go
Removing Support for TLS 1.0 and 1.1
> ARGO-3581 Removing Support for TLS 1.0 and 1.1

- doc/swagger/swagger.yaml
Changed the response output in the Trends request
> changed events with duration_in_minutes in trends section

- argo-web-api.spec
- version/version.go
> version bump 1.11.0

- doc/swagger/swagger.yaml
- routing/router.go
- routing/routes.go
- scripts/mongodb/populate_default_roles.js
- v3/ar/ar_test.go
- v3/ar/handlers.go
- v3/ar/models.go
- v3/ar/queries.go
- v3/ar/routing.go
- v3/ar/validations.go
- v3/ar/views.go
- website/docs/v3results.md
- website/sidebars.js
Goal: 
Display A/R results for top level groups supergroups and groups such as `PROJECTS` and `SERVICEGROUPS` in one call
The new call will be in /api/v3/ path
Example Request:
`HTTP GET /api/v3/results/REPORT_NAME?start_time=YYYY-MM-DDT00:00:00Z&end_time=YYYY-MM-DDT00:00:00Z&granularity=daily`
Example Response:
```json
{
"results": [
{
"name": "GROUP_A",
"type": "GROUP",
"results": [
{
"date": "2015-06-22",
"availability": "68.13896116893515",
"reliability": "50.413931144915935"
},
{
"date": "2015-06-23",
"availability": "75.36324059247399",
"reliability": "80.8138510808647"
}
],
"groups": [
{
"name": "ST01",
"type": "SITES",
"results": [
{
"date": "2015-06-22",
"availability": "66.7",
"reliability": "54.6",
"unknown": "0",
"uptime": "1",
"downtime": "0"
},
{
"date": "2015-06-23", …
```
> ARGO-3645 Serve a/r results for top level groups in v3 of api

- Jenkinsfile
Set docker image used to build docusaurus documentation to a stable verision.
> Set docker image to a stable version

- argo-web-api.spec
> Bump version in spec

- website/docs/tenants_and_feeds/downtimes.md
> Minor fix to downtimes documentation

- website/static/openapi/argo-web-api.yml
Update `server` property in openapi spec document to point to devel instance
> update server property in openapi specification

- app/topology/model.go
- app/topology/topology_test.go
- website/docs/topology/topology_service_types.md
- website/static/openapi/argo-web-api.yml
Added a tags field in service-types call
> ARGO-4048 add additional tags field list of service types

- v3/ar/routing.go
- v3/status/routing.go
> ARGO-4089 support OPTIONS for api v3 calls using resource-ids

- app/downtimes/controller.go
- app/downtimes/downtimes_test.go
- app/downtimes/model.go
- doc/swagger/swagger.yaml
- website/docs/tenants_and_feeds/downtimes.md
Align devel branch with master
> Align devel with master

- website/package-lock.json
- website/package.json
Bump loader-utils to v2.0.4 (ref: https://github.com/ARGOeu/argo-web-api/pull/471)
> ARGO-4114 Update docusaurus to v2.2.0

- argo-web-api.spec
- version/version.go
- Update spec
- Update version num
> Bump to v.1.13.1

- website/docs/topology/topology_service_types.md
- website/package-lock.json
- website/package.json
Bump docusaurus to 2.3.1 
Fix json formatting issue in topology service-types doc
> ARGO-4253 Bump docusaurus to 2.3.1 

- argo-web-api.spec
- version/version.go
> Bump to v.1.13.3

- Jenkinsfile
> Update jenkinsfile node image for doc building

- CHANGELOG.md
- version/version.go
> prep v2.0.0

- .github/workflows/docs.yml
Fix docs deployment through gh actions
> Fix docs deployment through gh actions

- Jenkinsfile
- Use checksec from docker image
- Export checksec results as xml
- Create a shell function that checks if a specific field has a specific value in the xml file - if not return 1 (end pipeline)
- For a list of pairs of fields/expected values run the function and check
> ARGO-5102 Add checksec in ci/cd pipeline

- go.mod
- go.sum
Update testify package to v1.11.1
> dep update testify v1.11.1
