ARGOeu/argo-web-api

README.md
app/availabilityProfiles/availabilityProfilesController.go
app/availabilityProfiles/availabilityProfilesView.go
app/availabilityProfiles/availabilityProfiles_test.go
ar-web-api.spec
utils/authentication/authenticate.go
utils/mongo/mongoQuery.go

- Issues Found: 
- That in some cases in update/delete responses (Avail.Profiles) the response header wasn't correctly formatted (Fixed)
- That when an id was provided for update/delete profile it was forwarded to the query before checking that the string is a valid ObjectID string. 
- Added proper xml responses when a profile is properly deleted or updated (Were not implemented)
- Added checks when poem definitions are missing in a profile to properly display results with an empty "poem" string

ARGO-105 Fix response headers on update/delete

---

utils/mongo/mongoQuery.go
utils/mongo/mongo_test.go

This utilizes a helpful mongo function that will be used to query the central argo_core db for api keys and return the tenant name plus information on tenant db, host/port it runs. 
Documentation has been added and also one test to test the function.

ARGO-124 FindAndProject function in mongo package

---

app/availabilityProfiles/availabilityProfilesController.go
app/availabilityProfiles/availabilityProfilesModel.go
app/availabilityProfiles/availabilityProfilesView.go
app/availabilityProfiles/availabilityProfiles_test.go

- Modified structs in Model-View and Test to support maps and additional attributes. Renamed collection as discussed.
- Changed the way we check the validity of the XML result in Read and Delete test functions - compare their schemas instead of trying to compare two strings (static expected xml and actual). The reason is that the GO runtime randomizes the map iteration order. So when we try to compare the produced xml view with a static one declared in unit test it always fails because the xml attributes' order is random. Added one more regex check in `TestDeleteProfile()` and `TestReadProfile()` functions.
- Added multi-tenant authentication support.
- Code style and godoc improvements.

ARGO-121 Refactored availabilityProfiles for multitenancy

---

app/factors/factorsController.go
app/factors/factorsModel.go
app/factors/factorsView.go
app/factors/factors_test.go
app/tenants/tenantsController.go
app/tenants/tenantsModel.go
app/tenants/tenantsView.go
app/tenants/tenants_test.go
main.go
utils/authentication/authenticate.go
utils/authentication/authenticate_test.go
utils/config/config.go
utils/mongo/mongo_test.go

* Added a tenants package based on MVC
* Added a List function for providing via GET verb and x-api-key authentication the current list of tenants
* Added an `AuthenticateAdmin` function in authenticate utils package (and unit tests)
* Change in default API configuration to use `argo_core` database (instead of `AR`)
* Added a new GET subrouter via which x-api-key headers are forwarded to API methods
The changes that need to be applied per package are the ones you may find in the `factors` package. This commit was only made so as to highlight what changes.

ARGO-124 Argo Administrators authentication mechanism

---

app/jobs/jobsController.go
app/jobs/jobsModel.go
app/jobs/jobsView.go
app/jobs/jobs_test.go
app/tenants/tenantsController.go
app/tenants/tenantsModel.go
app/tenants/tenantsView.go
app/tenants/tenants_test.go
main.go
utils/mongo/mongoQuery.go

__Note__:This PR has been branched from ARGO-119 (https://github.com/ARGOeu/argo-web-api/pull/85) so it should be merged after that 
Implements `app/jobs` package wich allows __per tenant__ to: 
- Create new job definitons (POST)
- List all (or a specific one) job information (GET)
- Update a job definition (PUT)
- Remove a job definition (DELETE)
All requests are authenticated against a registered tenant user by calling func: ./utils/mongo.authenticateTenant (introduced in PR:#80)
This authentication if succeeds returns a `MongoConfig` object holding information on the specific tenant's datastore 
Note: Job definition Model uses the same structures (Job, JobProfiles and JobTags) both for the mongo bson document interfacing and for the xml & json marshaling as seen in the next snippet …

ARGO-120  Job definitions for each tenant

---

utils/caches/handleCache.go
utils/config/config.go

Currently the default config for the web api doesn't use the cache option (cache = false) . However we have implemented two functions of LRU cache in `ngiAvailability`,`siteAvailability`, `serviceFlavorAvailability`, and `voAvailability` controllers eg.
```
caches.HitCache("vos", input, cfg)
```
```
caches.WriteCache("sites", input, output, cfg)
```
The `HitCache` and `WriteCache` functions are implemented around `Get` and `Set` functions of LRU cache module. The LRU cache is basically a key/value store which uses specific key names (eg. "ngis" and "sites") to store and retrieve the appropriate values. The cache is initialized once in init.go. 
One implementation we could have is to instantiate a unique cache instance for all tenants and hold the necessary information using tenant …

ARGO-139 Disable cache functionality until we refactor it to support multitenancy.

---

app/jobs/jobsModel.go
app/statusDetail/statusDetailController.go
app/statusDetail/statusDetailModel.go
app/statusDetail/statusDetailView.go
app/statusDetail/statusDetail_test.go

This request returns all the detailed status metric results
- Multitenancy added based on api_key used
- New parameter introduced: job (now results are produced by individual computational jobs and must retrieved by job name)
- using only job name we can retrieve: 
- grouping information used in this specific computational view (endpoint group,group_of_groups) 
- metric profile used in this specific computational view
unittest provided using seed data for two tenants

ARGO-130 multitenancy on status detail results

---

init.go
main.go
respond/respond.go
routing/router.go
routing/routes.go
utils/caches/handleCache.go
utils/logging/logger.go
utils/mongo/mongoQuery.go

ARGO-184 Update routing to cover new API signatures

---

Makefile

In the Makefile we specify the directories that will be included in
the tarball. This means that everytime we add a new directory we
have to update the Makefile.
Furthermore, the tarball does not include .git, which breaks the
building process when we attempt to build app.
With this fix we add all the files to the tarball.

Fixes make sources

---

app/results/Controller.go
app/results/Model.go
app/results/View.go
app/results/endpointgroup_test.go
app/results/routing.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go

Handles responses when either
1) results from non existent reports are requested for or
2) results for non existent groups in a given report are asked for
Covers `results` package. 
please review /cc @skanct @makistsantekidis

ARGO-210 Report not found

---

app/metricResult/controller.go
app/metricResult/metric_test.go
app/statusMsg/statusMsgModel.go
app/statusMsg/statusMsg_test.go
doc/api/status-results.md

While working on ARGO-219 I noticed that in the case of one detailed result we name the host level in the xml response as host. This PR brings homogeneity with the remaining status (timelines) responses if we want it. To be exact the XML response is changed from:
```
<root>
<report name="EUDAT_CRITICAL">
<group name="EUDAT_EL" type="EUDAT_GROUP">
<group name="EL-01-AUTH" type="EUDAT_SITE">
<group name="srv.typeA" type="service_type">
<host name="host01.eudat.gr">
<metric name="typeA.metric.Memory">
<status timestamp="2015-05-01T01:00:00Z" status="">
<summary>srv.typeA status is critical</summary>
<message>memory error: Out of memory </message>
</status>
</metric>
</host>
</group>
</group>
</group>
</report>
</root>
```
to 
```
<root>
<report name="EUDAT_CRITICAL">
<group name="EUDAT_EL" …
```

[Proposed] Change host to endpoint in case of detailed result

---

argo-web-api.spec

debuginfo is not supported in Go. When attempting to package the
argo-web-api as an RPM, the build process fails with the following
error:
*** ERROR: No build ID note found...

Disables extracting debug info

---

app/results/endpointgroup_test.go

- Instead of quering and remove test data, drop the collections entirely

Drop collections instead of removing data with query

---

app/results/Controller.go
app/results/endpointgroup_test.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go
app/statusEndpointGroups/controller.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpoints/controller.go
app/statusEndpoints/statusEndpoints_test.go
app/statusMetrics/controller.go
app/statusMetrics/statusMetrics_test.go
app/statusServices/controller.go
app/statusServices/statusServices_test.go
utils/mongo/mongoQuery.go

Each defined report in the Compute Engine is used to produce a different set of results. The results while produced and stored in datastore are tagged with the according report name for future reference.
In this PR, the argo-web-api uses the report's id (uuid) as a future reference and tags the results. This gives the flexibility to be able to update/edit report.name field without affecting the relationship with the already computed results
- Add GetRerportID in mongo package to easily retrieve report id by name 
- in pkg results use GetReportID and reportID to query results
- in pkg statusEndpointGroups, statusEndpoints, statusMetrics & statusServices use GetReportID and reportID to query results

ARGO-245 Reference results using report.id instead of report.name

---

doc/swagger/swagger.yaml

Create a swagger yaml definition of the argo-web-api. Begin with description of metric profile resource calls. 
- Describe calls under /api/v2/metric_profiles
- Use definition to avoid duplication of schema/structures

ARGO-262 Swagger yaml definitions for metric profiles

---

doc/swagger/swagger.yaml

Add definitions for aggregation profiles calls in swagger yaml. 
Describe calls under /api/v2/aggregation_profiles
Use definition to avoid duplication of schema/structures
continuing work based on PR: https://github.com/ARGOeu/argo-web-api/pull/173. To be merged after that one.

ARGO-263 Swagger yaml definitions for aggregation profiles

---

doc/swagger/swagger.yaml

Description
Add definitions for operations profiles calls in swagger yaml.
Implementation
Describe calls under /api/v2/operations_profiles
Use definition to avoid duplication of schema/structures
Notes
continuing work based on PR: #174. To be merged after that one.

ARGO-264 Swagger yaml definitions for operations profiles

---

app/statusEndpointGroups/routing.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpoints/routing.go
app/statusEndpoints/statusEndpoints_test.go
app/statusMetrics/routing.go
app/statusMetrics/statusMetrics_test.go
app/statusServices/routing.go
app/statusServices/statusServices_test.go

Status calls, when not using a name to specify a site, endpoint or service, require a trailing slash
Instead of creating a new subrouter, use the whole path pattern on each of the route definitions to make sure that the whole request route path gets validated against the pattern at once instead of multiple path prefixes. This change is required because the gorilla mux routing requires at least one slash as an argument when calling `Path` to register a new route.

[ARGO-283] Fix routes to not require trailing slash

---

argo-web-api.spec

Add GOPATH/bin to PATH in order for builder to be able to use godep tool

ARGO-302 Fix spec build options

---

app/statusEndpointGroups/routing.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpoints/routing.go
app/statusEndpoints/statusEndpoints_test.go
app/statusMetrics/routing.go
app/statusMetrics/statusMetrics_test.go
app/statusServices/routing.go
app/statusServices/statusServices_test.go
respond/respond.go

In case a wrong key is being used the following response should be returned:
```
{
"status": {
"message": "Unauthorized",
"code": "401",
"details": "You need to provide a correct authentication token using the header 'x-api-key'"
}
}
```
please review /cc @themiszamani @kaggis

ARGO-359 Fix response messages and code in case of wrong api key usage

---

app/results/Controller.go
app/results/Model.go
app/results/View.go
app/results/endpointgroup_test.go
app/results/routing.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go

Fixes in response messages within the `results` resource of the api. Also in case of empty result set responds with a proper "no results found" message. 
please review /cc @themiszamani @kaggis

ARGO-360 Fix response messages within results resource

---

app/factors/factorsController.go
app/factors/factors_test.go
doc/swagger/swagger.yaml

Fix in response body in case a wrong api key is used under the /factors resource. Also updated unit tests.
Includes also a minor fix in swagger spec file.

ARGO-395 Fix in response body in case wrong api-key is being used

---

app/factors/factors_test.go
app/factors/routing.go
app/results/endpointgroup_test.go
app/results/routing.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go
routing/routes.go

Under some API resources using a trailing slash character would not return a `404 Not Found` response. This PR fixes this. More in detail this includes:

ARGO-406 Return a 404 Not Found in all cases a trailing slash is used

---

app/results/Model.go
app/results/endpointgroup_test.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go

ARGO-405 Change in name of upper level body response in results resource

---

doc/swagger/swagger.yaml

Description
This (proposed) PR removes a duplicate definition that was discovered within
the swagger yaml definitions file. Apparently after some update on the publicly
available swagger editor the duplication is caught and marked as an error.

[Proposed] Remove duplicated definition

---

app/metricResult/controller.go
app/metricResult/metric_test.go
app/metricResult/routing.go
doc/swagger/swagger.yaml

Description
While working on central validation task (ARGO-405) I noticed the OPTIONS verb was
not supported under the /api/v2/metric_result resource. This proposed PR adds this
functionality on the given resource and also adds the underlying signature and response
schemas into the swagger yaml definition file.

[Proposed] Support OPTIONS verb under metricResult resource

---

app/aggregationProfiles/aggregationProfiles_test.go
app/factors/factors_test.go
app/metricProfiles/metricProfiles_test.go
app/metricResult/metric_test.go
app/operationsProfiles/operationsProfiles_test.go
app/recomputations2/recomputation_test.go
app/reports/reports_test.go
app/results/endpointgroup_test.go
app/results/routing.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go
app/statusEndpointGroups/routing.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpoints/routing.go
app/statusEndpoints/statusEndpoints_test.go
app/statusMetrics/routing.go
app/statusMetrics/statusMetrics_test.go
app/statusServices/routing.go
app/statusServices/statusServices_test.go
app/tenants/tenants_test.go
respond/respond.go
respond/wrappers.go
scripts/mongodb/populate_default_roles.js
utils/authentication/authenticate.go
utils/authorization/authorize.go
utils/config/config.go

Implement authorization logic (as in argo-messaging) using roles
In argo-messaging two collections are used for auth: `users` and `roles`
In argo-web-api user information is holded in `tenants` collection. User list of roled was added as a new field for each user in `tenants` collection for eg:
```json
{
"name" : "TENANT",
"db_conf" : [
],
"users" : [
{
"name" : "User_admin",
"email" : "useradmin@email.example.com",
"api_key" : "ADMINKEY",
"roles" : [
"admin",
"member"
]
},
{
"name" : "User_viewer",
"email" : "userview@email.example.com",
"api_key" : "VIEWERKEY",
"roles" : [
"viewer"
]
}
]
}
```
- `roles` collection was added with permission reflection argo-web-api's routes 
for eg:
```json
[{ "resource" : "reports.get", "roles" : [ "admin", "editor", "viewer" ] },
{ "resource" : …
```

ARGO-417 Implement Authorization logic using roles

---

doc/v2/docs/validations.md
respond/validators.go

The Granularity parameter is only relevant for a/r result requests. For status requests granularity is not supported. In order to avoid confusion, if a user provides granularity parameter during status requests the following response is returned:
```json
{
"status": {
"message": "Bad Request",
"code": "400"
},
"errors": [
{
"message": "Granularity parameter should not be used in status results",
"code": "400",
"details": "Granularity parameter is valid only for a/r result requests, not for status results"
}
]
}
```

ARGO-450 Granularity parameter should not be accepted in status requests

---

main.go

The default cipher suite in the crypto/tls package contains secure
ciphers, which are compatible with centos5 without compromising the
security of the server

ARGO-528 Use the default cipher suite

---

app/results/Controller.go

The web-api monthly supergroup aggregation contained a bug which in the monthly availability calculation excluded (wrongly) days that had undefined reliabilities but well definied availabilities. The error was in a mongo query which computes the results on the fly and responds.
In order not to break the query to multiple ones and cause refactoring changes to surrounding objects a single query remained *but* with the following changes:
- Since monthly av/rel figures are produced with weighted averages each item gets two new weights (weightAv and weightRel). 
- If item's availability is undefined then the corresponding weight (weightAv) will be set to 0 so as not to affect the sums/averages
- If item's reliability is undefined then the corresponding weight (weightRel) will be set to 0 so as …

ARGO-541 Fix MonthlySupergroup avail/rel aggregation bug

---

argo-web-api.conf

The web api writes its event stream, unbuffered, to stdout, following
the twelve-factor methodology. This commit changes the init script to
pipe stdout to logger.

ARGO-591 Enables logging to syslog

---

app/tenants/controller.go
app/tenants/model.go
app/tenants/tenants_test.go
doc/v2/docs/tenants.md
respond/wrappers.go
scripts/mongodb/populate_default_roles.js
utils/authentication/authenticate.go

Super admins are the only users that have access to tenant information. They also have CRUD authorization. There are cases that client need access to tenant info for read-only purposes. 
Implement a super_admin_restricted user that will have read-only access to list of tenants. Hide some internal tenant information (like tenant's db conf and tenant's user list) from restricted super admin

ARGO-1099 Add read-only super-admin

---

app/thresholdsProfiles/controller.go
app/thresholdsProfiles/model.go
app/thresholdsProfiles/routing.go
app/thresholdsProfiles/thresholdsProfiles_test.go
app/thresholdsProfiles/view.go
doc/swagger/swagger.yaml
doc/v2/docs/threshold_profiles.md
routing/routes.go

Hold threhsold profile information in argo-web-api

ARGO-1260 Implement CRUD on threshold profiles resource

---

app/tenants/controller.go
app/tenants/model.go
app/tenants/routing.go
app/tenants/tenants_test.go
app/tenants/view.go
doc/swagger/swagger.yaml
doc/v2/docs/tenants.md

Related to: https://github.com/ARGOeu/argo-streaming/pull/88
Show tenant's argo-engine status through api call
- signature: `GET /api/v2/admin/tenants/{tenant_id}/status` 
Update tenant's argo-engine status through api call
- signature: `PUT /api/v2/admin/tenants/{tenant_id}/status`

ARGO-1298 Show/Update tenant's argo-engine status

---

app/statusEndpointGroups/controller.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpointGroups/view.go
app/statusEndpoints/controller.go
app/statusEndpoints/statusEndpoints_test.go
app/statusEndpoints/view.go
app/statusMetrics/controller.go
app/statusMetrics/statusMetrics_test.go
app/statusMetrics/view.go
app/statusServices/controller.go
app/statusServices/statusServices_test.go
app/statusServices/view.go
doc/v2/docs/status.md

When presenting a status timeline go the extra mile and display the last point in the timeline even if the status doesn't change
for e.g. from:
```
{
"groups": [
{
"name": "FOO",
"type": "SITES",
"statuses": [
{
"timestamp": "2018-06-22T00:00:00Z",
"value": "OK"
}
]
}
]
}
```
go to:
```
{
"groups": [
{
"name": "FOO",
"type": "SITES",
"statuses": [
{
"timestamp": "2018-06-22T00:00:00Z",
"value": "OK"
},
{
"timestamp": "2018-06-22T23:59:59Z",
"value": "OK"
}
]
}
]
}
```

ARGO-451 Close status timelines with latest daily result

---

app/topology/controller.go
app/topology/model.go
app/topology/routing.go
app/topology/topology_test.go
app/topology/view.go
doc/swagger/swagger.yaml
doc/v2/docs/topology.md
doc/v2/mkdocs.yml
routing/routes.go
scripts/mongodb/populate_default_roles.js

Per report, serve topology details for groups, services included in the report 
Implement the following method with request signature 
`GET /api/v2/topology/{report_name}?date=2018-06-02`
which responds with in the following style:
```
```json
{
"status": {
"message": "application/json",
"code": "200"
},
"data": {
"group_count": 2,
"group_type": "PROJECTS",
"group_list": [
"PROJECT_A",
"PROJECT_B"
],
"endpoint_group_count": 3,
"endpoint_group_type": "SERVICEGROUPS",
"endpoint_group_list": [
"SGROUP_A",
"SGROUP_B",
"SGROUP_C"
],
"service_count": 8,
"service_list": [
"service_type_1",
"service_type_2",
"service_type_3",
"service_type_4",
"service_type_5",
"service_type_6",
"service_type_7",
"service_type_8"
]
}
}
```
which includes 
- count numbers for groups, endpoint groups and services
- …
```

ARGO-1268 Serve topology statistics per report

---

app/tenants/model.go
app/tenants/tenants_test.go

Fix annotation typo so the json field is exported as `configuration_profile` and not as `ConfigProf`

ARGO-1435 Fix configuration_profile json field in tenant status call

---

app/tenants/controller.go
app/tenants/model.go
app/tenants/tenants_test.go
doc/swagger/swagger.yaml
doc/v2/docs/tenants.md

admin/tenant/status request returns a detailed json about tenant's status in argo engine but instead of iterating through numerous fields, we need a quick boolean field to show us that everything is ok. 
`total_status` boolean field is added in the json body which is calculated on the fly from the values of the other specific status fields
example:
```json
"status": {
"total_status": false,
"ams": {
"metric_data": {
"ingestion": false,
"publishing": false,
"status_streaming": false,
"messages_arrived": 0
},
...
}
```
- Add TotalStatus field in tenant.StatusDetail structure
- Implement tenants.calcTotallStatus() 
- Refactor tenants.ListStatus() handler to use calcTotalStatus() method
- Update unit tests (add example with both false/true general statuses)
- Update Docs

ARGO-1438 Implement tenant general status

---

app/results/Controller.go
app/results/Model.go
app/results/View.go
app/results/endpoint_test.go
app/results/routing.go
doc/swagger/swagger.yaml
doc/v2/docs/results.md

Compute engine calculates a/r scores on endpoint level. Argo web-api should expose those results. Extend current results path to be able to drill down to endpoint results:
- Current results path example:
`/v2/api/results/{REPORT}/{group_type}/{group_name}/services/{service}`
- Extended path variations for endpoint results:
`/v2/api/results/{REPORT}/{group_type}/{group_name}/services/{service}/endpoints`
`/v2/api/results/{REPORT}/{group_type}/{group_name}/services/{service}/endpoints/{endpoint_name}`
and provide also a direct shortcut to get endpoint a/r results under a group: 
`/v2/api/results/{REPORT}/{group_type}/{group_name}/endpoints`
`/v2/api/results/{REPORT}/{group_type}/{group_name}/endpoints/{endpoint_name}`

ARGO-1680 serve endpoint a/r results

---

app/tenants/controller.go
app/tenants/model.go
app/tenants/tenants_test.go
doc/swagger/swagger.yaml
doc/v2/docs/tenants.md

Whenever a new tenant is created, for each one of its users, use the **uuid generator** inside of the **mongo** package to generate and assign them **uuids** in the field **id**
Also for the update tenant call, preserve the id of the users that hold the same apikey as before, and generate new ids for new users.

ARGO-1744 Add UUID for tenant's users

---

app/statusEndpointGroups/controller.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpointGroups/view.go
app/statusEndpoints/controller.go
app/statusEndpoints/statusEndpoints_test.go
app/statusEndpoints/view.go
app/statusMetrics/controller.go
app/statusMetrics/statusMetrics_test.go
app/statusMetrics/view.go
app/statusServices/controller.go
app/statusServices/statusServices_test.go
app/statusServices/view.go

When asking for multime status timelines at once, only the last one gets an end of day status point that closes the timeline
- Refactor create view at statusEndpointGroups package to fix the issue
- Refactor create view at statusServices package to fix the issue
- Refactor create view at statusEndpoints package to fix the issue
- Refactor create view at statusMetrics package to fix the issue
- Remove closeTimeline function
- Refactor controllers

ARGO-1958 Fix add end of day point in multiple status timelines

---

app/metricResult/controller.go
app/metricResult/metric_test.go
app/metricResult/model.go
app/metricResult/routing.go
app/metricResult/view.go
doc/swagger/swagger.yaml
doc/v2/docs/metrics.md
utils/mongo/mongoQuery.go

Give the ability to query all daily metric data results for a specific host in a single request
in pkg `metricResult`:
- Create `GetMultipleMetricResults` handler 
- Create a mongo aggregation query in method `prepareMultipleQuery`
- Create new view for multiple metric results
- Update routing to use the pattern `/metric_result/{hostname}?exec_time={date_param}`
- Update docs

ARGO-1964 Return all daily metric data for specific host and date

---

app/metricResult/controller.go
app/metricResult/metric_test.go
app/metricResult/model.go
app/metricResult/view.go
doc/swagger/swagger.yaml
doc/v2/docs/metrics.md

Add optional filter parameter when request list of metric data for host
- Add optional `filter` parameter in request handler
- Use optional filter parameter in method that prepares query for list of metric data
- Update docs

ARGO-1983 Add filter param to return metric result list

---

app/recomputations2/Controller.go
app/recomputations2/Model.go
app/recomputations2/recomputation_test.go
app/recomputations2/routing.go
doc/swagger/swagger.yaml
doc/v2/docs/recomputations.md

Give the ability to change recomputation status through web api 
Allow to hold a history of status changes for each recomputation 
- In recomputation model add new field: `History`   that holds a list of (status,timestamp) items 
- add a new api request exclusively for changing recomputation statuses 
request signature: `POST /api/v2/recomputations/{id}/status`
accepts a POST BODY e.g.: `{"status": "approved"}` Status history is updated on the recomputation item
- add a new api request exclusively for reseting a recomputation status history
request signature: `DELETE /api/v2/recomputations/{id}/status

ARGO-1997 Change recomputation status through web-api

---

app/latest/controller.go
app/latest/latest_test.go
doc/swagger/swagger.yaml
doc/v2/docs/latest.md

Make `/api/v2/latest` to use parameter `strict=false` by default.
If user wants to use strict mode, it must be supplied as a url parameter `strict=true`

ARGO-2058 Set strict=false by default in latest results call

---

app/latest/controller.go
app/latest/latest_test.go

:warning: to be merged after https://github.com/ARGOeu/argo-web-api/pulls/303
Fix `/api/v2/latest` call to actually use `limit` url parameter when `strict` mode is on
Fix `/api/v2/latest` call to actually use `filter` url parameter when `strict` mode is on
Implementation:
- Refactor prepareQuery method in `latest` package to utilize the same match query both in aggregated or simple query call
- Aggregation query needs also a sorting with limit part to simulate the same sorting & limit function of the simple query
- Add unit tests

ARGO-2057 Fix latest results strict mode to honor limit parameter

---

app/latest/controller.go
app/latest/latest_test.go
app/latest/model.go
version/version.go

Version bump to 1.8.1
Issue: 
`/v2/api/latest` when `strict=true` returns the correct list of results but they are order by group name and not by time
Fix:
- After computing the correct results add a last pipeline stage to sort by time 
- Fix a data prep issue in unit test

ARGO-2059 Fix latest strict result order by time instead of group name

---

app/operationsProfiles/controller.go
app/operationsProfiles/model.go
app/operationsProfiles/operationsProfiles_test.go
doc/swagger/swagger.yaml
doc/v2/docs/operations_profiles.md
utils/utils.go

Give the ability to maintain historic version of the operations profiles when they change
Add an extra url parameter `date` in operations_profiles request signatures (GET, POST, PUT)
:red_circle:  note that a specific indexing scheme should be prepared in operations_profile mongodb collection in order the queries to work correctly

ARGO-2002 Add history functionality for ops profiles

---

app/operationsProfiles/controller.go
app/operationsProfiles/model.go
app/operationsProfiles/operationsProfiles_test.go
doc/swagger/swagger.yaml
doc/v2/docs/operations_profiles.md
utils/utils.go

Give the ability to maintain historic version of the operations profiles when they change
Add an extra url parameter `date` in operations_profiles request signatures (GET, POST, PUT)
:red_circle:  note that a specific indexing scheme should be prepared in operations_profile mongodb collection in order the queries to work correctly

ARGO-2002 Add History for operations profiles

---

app/metricProfiles/controller.go
app/metricProfiles/metricProfiles_test.go
app/metricProfiles/model.go
app/metricProfiles/view.go
app/operationsProfiles/controller.go
app/weights/controller.go
app/weights/model.go
app/weights/routing.go
app/weights/view.go
app/weights/weights_test.go
doc/swagger/swagger.yaml
doc/v2/docs/metric_profiles.md
doc/v2/docs/weights.md
doc/v2/mkdocs.yml
routing/routes.go
scripts/mongodb/populate_default_roles.js

:warning: to be merged after https://github.com/ARGOeu/argo-web-api/pull/301
Give the ability to maintain historic version of the metric profiles when they change
Add an extra url parameter `date` in metric_profiles request signatures (GET, POST, PUT)
:red_circle:  note that a specific indexing scheme should be prepared in metric_profiles mongodb collection in order the queries to work correctly

ARGO-2000 Add history functionality for metric profiles

---

app/aggregationProfiles/aggregationProfiles_test.go
app/aggregationProfiles/controller.go
app/aggregationProfiles/model.go
app/aggregationProfiles/view.go
app/operationsProfiles/controller.go
doc/swagger/swagger.yaml
doc/v2/docs/aggregation_profiles.md

:warning: to be merged after https://github.com/ARGOeu/argo-web-api/pull/306
Give the ability to maintain historic version of the aggregations profiles when they change
Add an extra url parameter `date` in aggregations_profiles request signatures (GET, POST, PUT)
:red_circle:  note that a specific indexing scheme should be prepared in aggregations_profiles mongodb collection in order the queries to work correctly

ARGO-2001 Add history functionality for aggregation profiles

---

app/aggregationProfiles/controller.go
app/operationsProfiles/controller.go
app/thresholdsProfiles/controller.go
app/thresholdsProfiles/model.go
app/thresholdsProfiles/thresholdsProfiles_test.go
doc/swagger/swagger.yaml
doc/v2/docs/threshold_profiles.md

:warning: to be merged after https://github.com/ARGOeu/argo-web-api/pull/308
Give the ability to maintain historic version of the thresholds profiles when they change
Add an extra url parameter `date` in thresholds_profiles request signatures (GET, POST, PUT)
:red_circle:  note that a specific indexing scheme should be prepared in thresholds_profiles mongodb collection in order the queries to work correctly

ARGO-2088 Add historic functionality for thresholds profiles

---

app/aggregationProfiles/aggregationProfiles_test.go
app/aggregationProfiles/controller.go
app/metricProfiles/controller.go
app/metricProfiles/metricProfiles_test.go
app/operationsProfiles/controller.go
app/operationsProfiles/operationsProfiles_test.go
app/thresholdsProfiles/controller.go
app/thresholdsProfiles/thresholdsProfiles_test.go

Issue: When profiles are emtpy HTTP GET /*_profiles list returns 404 instead of an empty list
Fix: Change List controllers in operations, metrics, aggregation and thresholds profiles to return 200 OK and empty list instead of a 404 not foun

ARGO-2125 Fix regression of returning 404 when profile list were empty

---

app/weights/controller.go
app/weights/model.go
app/weights/weights_test.go
doc/swagger/swagger.yaml
doc/v2/docs/weights.md

Give the ability to maintain historic version of the weight resources when they change
Add an extra url parameter `date` in weights request signatures (GET, POST, PUT)
When using date with GET the closest historic version of the profile is retrieved. If date is ommited the most recent weights resource is retrieved
When using date with POST a specific historic entry is created (new snapshot)
When using date with PUT an update is performed on a specific historic version of the weights resource
:red_circle:  note that a specific indexing scheme should be prepared in weights mongodb collection in order the queries to work correctly

ARGO-2099 Add historic versioning to weights resources

---

app/downtimes/controller.go
app/downtimes/downtimes_test.go
app/downtimes/model.go
app/weights/weights_test.go
doc/v2/docs/downtimes.md

Give the ability to maintain historic version of the downtimes resources when they change
Add an extra url parameter `date` in downtimes request signatures (GET, POST, PUT)
When using date with GET the closest historic version of the profile is retrieved. If date is ommited the most recent downtimes resource is retrieved
When using date with POST a specific historic entry is created (new snapshot)
When using date with PUT an update is performed on a specific historic version of the downtimes resource
:red_circle:  note that a specific indexing scheme should be prepared in downtimes mongodb collection in order the queries to work correctly

ARGO-2137 Add historic versioning to downtimes resources

---

app/downtimes/controller.go
app/weights/controller.go
routing/routes.go

Fix 404 response when lists empty
- Remove `weights` and `downtimes` prefix from outer router (already declared in subrouter)
- Remove 404 check when `weights` and `downtimes` lists are empty

ARGO-2142 Fix double routing prefixes for weights and downtimes.

---

app/latest/latest_test.go

Change db name used in unit tests to be consistent with context

ARGO-2184 Fix db reference name in package latest unittest

---

Jenkinsfile
app/latest/latest_test.go

Constructed JenkinsFile Pipeline with the following stages
- Added a `build` stage: test actual build if succeeds or not
- Added a `test` stage: Run unit tests and produce coverage reports. Capture results in jenkins
- Added a `package` stage: Try to create a current temp package (update version in spec file by adding latest commit hash and commit date) and capture the artifact only in jenkins. Usefull if having changes in spec files etc
- Added a `package for devel` stage: Change spec version with latest commit hash and commit date and create a package for devel repo. Capture artifact in jenkins. Upload devel rpm to repo
- Added a `package for prod` stage: Build production rpm with explicit spec version. Capture artifact in jenkins. Upload devel rpm to repo

ARGO-2126 Create jenkins file for argo-web-api

---

app/topology/controller.go
app/topology/model.go
app/topology/routing.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md
doc/v2/docs/topology_stats.md
doc/v2/mkdocs.yml
scripts/mongodb/populate_default_roles.js

Allow to insert endpoint topology information to argo-web-api
In existing `topology` package implement a new api call in the following route:
`POST /api/v2/topology/endpoints`
The model that describes each item in endpoint topology per day is the following:
```json
{ 
"date" : "date representation in daily format YYYY-DD-MM",
"hostname": "endpoint's hostname",
"service": "endpoint's service type",
"group" :"endpoint group that the endpoint belongs to",
"type": "endpoint group type like SITES or SERVICEGROUPS or other",
"tags": { "key": "value", "key2": "value2}
}
```
Each daily topology consists of a list of the above items like in the following example:
```json
[
{"group": "SITE_A", "hostname": "host1.site-a.foo", "type": "SITES", "service": "a.service.foo", "tags": {"scope": "TENANT", …
```

ARGO-2106 Insert Endpoint Group Topology per day

---

app/topology/controller.go
app/topology/model.go
app/topology/routing.go
app/topology/topology_test.go
app/topology/view.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md
doc/v2/docs/topology_stats.md
doc/v2/mkdocs.yml
respond/respond.go
scripts/mongodb/populate_default_roles.js

:warning: to be reviewed after https://github.com/ARGOeu/argo-web-api/pull/326
Diplay endpoint topology per day 
In existing topology package implement a new api call in the following route:
`GET /api/v2/topology/endpoints?date=2019-12-12`
The model that describes each item in endpoint topology per day is the following:
```
{ 
"date" : "date representation in daily format YYYY-DD-MM",
"hostname": "endpoint's hostname",
"service": "endpoint's service type",
"group" :"endpoint group that the endpoint belongs to",
"type": "endpoint group type like SITES or SERVICEGROUPS or other",
"tags": { "key": "value", "key2": "value2}
}
```
Each daily topology consists of a list of the above items like in the following example:
```
[
{"date"="2019-12-12", "group": "SITE_A", "hostname": …
```

ARGO-2108 List Endpoint topology per day

---

app/topology/controller.go
app/topology/model.go
app/topology/routing.go
app/topology/topology_test.go
app/topology/view.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md
doc/v2/docs/topology_stats.md
doc/v2/mkdocs.yml
respond/respond.go
scripts/mongodb/populate_default_roles.js

:warning: to be reviewed after: https://github.com/ARGOeu/argo-web-api/pull/328
Allow to delete topology endpoints for a specific date 
example
```
DELETE /v2/api/topology/endpoints?date=YYYY-MM-DD
```

ARGO-2109 Delete endpoint topology for specific date

---

app/topology/controller.go
app/topology/model.go
app/topology/routing.go
app/topology/topology_test.go
app/topology/view.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md
doc/v2/docs/topology_groups.md
doc/v2/mkdocs.yml
respond/respond.go
scripts/mongodb/populate_default_roles.js

:warning: to be reviewed after /pull/328
Allow to insert group topology information to argo-web-api
In existing `topology` package implement a new api call in the following route:
`POST /api/v2/topology/groups`
The model that describes each item in group topology per day is the following:
```json
{ 
"date" : "date representation in daily format YYYY-DD-MM",
"group" :"group name",
"type": "group type like PROJECTS, NGIS or other",
"subgroup": "subgroup name that is contained in this group",
"tags": { "key": "value", "key2": "value2}
}
```
Each daily topology consists of a list of the above items like in the following example:
```json
[
{
"group": "NGIA",
"type": "NGIS",
"service": "SITEA",
"tags": {
"scope": "FEDERATION",
"infrastructure": "Production",
"certification": "Certified"
}
},
{ …
```

ARGO-2110 Insert group topology list per day

---

app/topology/controller.go
app/topology/routing.go
app/topology/topology_test.go
app/topology/view.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md
doc/v2/docs/topology_groups.md
scripts/mongodb/populate_default_roles.js

:warning: to be reviewed after /pull/330
Allow to list group topology information per date
In existing `topology` package implement a new api call in the following route:
`GET /api/v2/topology/groups`
The model that describes each item in group topology per day is the following:
```json
{ 
"date" : "date representation in daily format YYYY-DD-MM",
"group" :"group name",
"type": "group type like PROJECTS, NGIS or other",
"subgroup": "subgroup name that is contained in this group",
"tags": { "key": "value", "key2": "value2"}
}
```
Each daily topology consists of a list of the above items like in the following example:
```json
[
{
"group": "NGIA",
"type": "NGIS",
"service": "SITEA",
"tags": {
"scope": "FEDERATION",
"infrastructure": "Production",
"certification": "Certified"
}
},
{
"group": …
```

ARGO-2112 List group topology per day

---

app/topology/controller.go
app/topology/routing.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_groups.md
scripts/mongodb/populate_default_roles.js

:warning: to be reviewed after: https://github.com/ARGOeu/argo-web-api/pull/331
Allow to delete group endpoints for a specific date 
example
```
DELETE /v2/api/group/endpoints?date=YYYY-MM-DD
```

ARGO-2106 Delete group topology

---

app/topology/controller.go
app/topology/model.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md

When listing endpoint topology allow filtering results by using the basic fields
`GET /api/v2/topology/endpoints?date=YYYY-MM-DD&group=val1&type=val2&hostname=val3&service=val4`
User can also use wildcards* in filter values

ARGO-2185 Support basic filtering when listing endpoint topology

---

app/topology/controller.go
app/topology/model.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_groups.md

When listing group topology allow filtering results by using the basic fields
`GET /api/v2/topology/groups?date=YYYY-MM-DD&group=val1&type=val2&subgroup=val3`
User can also use wildcards* in filter values

ARGO-2189 Support basic filtering when listing group topology

---

app/topology/controller.go
app/topology/model.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md

Allow users to filter endpoint topology using tags key value pairs
Allow a new query paramterer named tags to be used to define tag key:value pair filters in the following pattern:
`GET /v2/api/topology/endpoints?tags=key1:value1,key2:value2`

ARGO-2186 Support tags filtering in endpoint topology

---

app/topology/controller.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_endpoints.md
doc/v2/docs/topology_groups.md

Allow users to filter group topology using tags key value pairs
Allow a new query paramterer named tags to be used to define tag key:value pair filters in the following pattern:
`GET /v2/api/topology/groups?tags=key1:value1,key2:value2`

ARGO-2190 Support tags filtering when listing group topology

---

app/topology/controller.go
app/topology/routing.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_groups.md
scripts/mongodb/populate_default_roles.js

Give the ability to fitler group topology based on report configuration. Each report has a topology schema reference fields which states the type of top-level and bottom-level groups. Api should read the top-level group type stated at the report and filter the group topology accordingly. The new feature is to be implemented at the following path 
`GET /api/v2/topology/groups/by_report/{report_name}`

ARGO-2181 Use report topology option to filter group topology

---

app/topology/controller.go
app/topology/routing.go
app/topology/topology_test.go
doc/swagger/swagger.yaml
doc/v2/docs/topology_groups.md
scripts/mongodb/populate_default_roles.js

When filtering group topology by calling `GET /api/v2/topology/groups/by_report/{report_name}` apply report's filter tags as filters to the topology
Each report definition has a filter dictionary named `filter_tags` like the following
```json
{
"filter_tags": [
{
"name": "infrastructure",
"value": "Production",
"context": "argo.group.filter.tags"
},
{
"name": "certification",
"value": "Certified",
"context": "argo.group.filter.tags"
}
]
}
```
Argo-web-api will check for filter tags containing a specific context = "argo.group.filter.tags" and apply the filters correctly to the topology

ARGO-2192 Use report's filter tags field to automatically filter group topology

---

Jenkinsfile
app/aggregationProfiles/aggregationProfiles_test.go
app/aggregationProfiles/controller.go
app/downtimes/controller.go
app/downtimes/downtimes_test.go
app/metricProfiles/controller.go
app/metricProfiles/metricProfiles_test.go
app/operationsProfiles/controller.go
app/operationsProfiles/operationsProfiles_test.go
app/thresholdsProfiles/controller.go
app/thresholdsProfiles/thresholdsProfiles_test.go
app/topology/controller.go
app/topology/routing.go
app/topology/topology_test.go
app/weights/controller.go
app/weights/weights_test.go
doc/swagger/swagger.yaml
doc/v2/docs/reports.md
doc/v2/docs/topology_endpoints.md

ARGO-2188 Use report's filter tags field to filter endpoint topology by tags
Allow filtering of endpoint topology using a report reference. To filter endpoint topology correctly we must first apply report's filtering options to the top level groups and from there keep only the endpoints that are part of those groups. We apply further endpoint related filters to the resulting endpoint dataset
Use mongo aggreagation and specifically a `$lookup` pipeline stage to perform a left join between filtered groups and endpoints. The aggregation pipeline can be summarized in the following steps:
1) start aggregation on group topology collection
2) $match stage: match groups by applying report's group related filters 
3) $lookup stage: for each group record in result, lookup the endpoint collection …

ARGO-2187 Use report topology to filter endpoint items

---

app/topology/controller.go
app/topology/model.go
app/topology/topology_test.go

Support composite filters in topology calls. For example give the ability to filter endpoints by multiple field values such as: group="SITEA" and group = "SITEB" by repeating the url query parameters in the following way:
`/api/v2/topology/endpoints?group=SITEA&group=SITEB`

ARGO-2238 Support composite filters in topology

---

app/metricProfiles/controller.go
app/metricProfiles/metricProfiles_test.go
app/metricProfiles/model.go
doc/swagger/swagger.yaml
doc/v2/docs/metric_profiles.md

Add a new field named: `description` in metric profiles

ARGO-2249 Add description field to metric profiles

---

app/aggregationProfiles/aggregationProfiles_test.go
app/aggregationProfiles/controller.go
app/downtimes/controller.go
app/downtimes/downtimes_test.go
app/metricProfiles/controller.go
app/metricProfiles/metricProfiles_test.go
app/operationsProfiles/controller.go
app/operationsProfiles/operationsProfiles_test.go
app/thresholdsProfiles/controller.go
app/thresholdsProfiles/thresholdsProfiles_test.go
app/topology/controller.go
app/topology/routing.go
app/topology/topology_test.go
app/weights/controller.go
app/weights/weights_test.go
respond/respond.go
utils/utils.go

Date optional query param in historic profile request was not validated properly due to err handling bug

ARGO-2274 Fix date input validation checks in historic profiles

---

app/results/Controller.go
app/results/Model.go
app/results/View.go
app/results/endpoint_test.go
app/results/routing.go
doc/swagger/swagger.yaml
doc/v2/docs/results.md

Give the ability to argo-web-api to display a flat list of all available endpoint a/r results per report (without having to navigate through endpoint groups and services)

ARGO-2227 Feature: argo-web-api flat endpoint list a/r

---

app/statusFlatMetrics/controller.go
app/statusFlatMetrics/model.go
app/statusFlatMetrics/routing.go
app/statusFlatMetrics/statusFlatMetrics_test.go
app/statusFlatMetrics/view.go
app/statusMetrics/statusMetrics_test.go
app/statusMetrics/view.go
doc/swagger/swagger.yaml
doc/v2/docs/status.md
routing/routes.go

Goal
====
Provide a flat list of status results for all avaliable service endpoint metrics filtered by a specific metric
Implementation
============

ARGO-2305 Flat list of status results by metric type

---

postman/argo-web-api_tests.json

ARGO-2496 Provide profile and report postman tests

---

app/feeds/controller.go
app/feeds/feeds_test.go
app/feeds/model.go
app/feeds/routing.go
app/feeds/view.go
doc/v2/docs/feeds.md
doc/v2/mkdocs.yml
routing/routes.go
scripts/mongodb/populate_default_roles.js

Give tha ability to argo-web-api to store and serve information about topology feeds in the following path
`/api/v2/feeds/topoloy`
Give the ability to
- Update feed topology with HTTP PUT
- Get feed topology with HTTP GET
Feed topology information body in json:
```
{
"type": "gocdb",
"feed_url": "https://somewhere.foo.bar/topology/feed",
"paginated": "true",
"fetch_type": [
"item1",
"item2"
],
"uid_endpoints": "endpointA"
}
```

ARGO-2509 Provide topology feed parameters

---

app/feeds/feeds_test.go
app/feeds/routing.go

Feeds module has the prefix '/feeds/ both declared in the main router and in the modules sub-router resulting in a path such as /api/v2/feeds/feeds/. Remove /feeds prefix from sub-router to resolve the issue

ARGO-2572 Fix feeds routing issue

---

app/statusEndpoints/statusEndpoints_test.go
app/statusFlatEndpoints/statusFlatEndpoints_test.go
app/tenants/controller.go
app/tenants/routing.go
app/tenants/tenants_test.go
app/tenants/view.go
doc/swagger/swagger.yaml
scripts/mongodb/populate_default_roles.js
website/docs/tenants.md

Add a new web-api call to quick add a new user to an existing tenant:
`POST /api/v2/tenants/{tenant_id}/users`
With the following body:
```json
{
"name":"new_user",
"email":"new_user@email.com",
"roles": [
"admin"
]
}`
```
Implementation:
Extras:

ARGO-2473 Tenant create user

---

app/downtimes/controller.go
app/downtimes/downtimes_test.go
app/downtimes/model.go
app/downtimes/routing.go
app/downtimes/view.go
doc/swagger/swagger.yaml
scripts/mongodb/populate_default_roles.js
website/docs/downtimes.md

Change downtime management:
- Make downtimes global per day (no namespacing with specific name or id per downtime set)
- Treat downtime resource as topology resources (updates with failsafe: verify by clearing a downtime set of a specific date before creating a new downtime set for that particular date)
- Update unit tests
- Update routing
- Update docs

ARGO-2651 Remove name,id namespacing from daily downtimes

---

app/feeds/controller.go
app/feeds/feeds_test.go
app/feeds/model.go
app/feeds/routing.go
app/feeds/view.go
doc/swagger/swagger.yaml
website/docs/feeds.md

Give tha ability to argo-web-api to store and serve information about weights feeds in the following path
/api/v2/feeds/weights
Give the ability to
- Update feed weights params with HTTP PUT
- Get feed weights params with HTTP GET
Feed weights information body in json:
```
{
"type": "vapor",
"feed_url": "https://somewhere.foo.bar/weights/feed",
"weight_type" : "hepspec2016 cpu",
"group_type" : "SITES"
}
```

ARGO-2630 Implement weights feed resource

---

app/recomputations2/Controller.go
app/recomputations2/recomputation_test.go
doc/swagger/swagger.yaml
respond/validators.go
website/docs/recomputations.md

Give the ability to filter recomputation by affected date and report name. This will be helpfull in daily computation jobs to be able to retrieve all relevant recomputations for that day and report directly from the api it self
Provide two optional filters by using query parameters in the api call:
`HTTP GET /api/v2/recomputations?report={report_name}&date={YYYY-MM-DD}`

ARGO-2703 Implement filter recomputations by date and report

---

Jenkinsfile

Due to a change in the Jenkinsfiles orientation this directive is not any more useful.

Remove triggering swagger job directive

---

app/topology/controller.go
app/topology/model.go
app/topology/routing.go
app/topology/topology_test.go
app/topology/view.go
doc/swagger/swagger.yaml
scripts/mongodb/populate_default_roles.js
website/docs/topology_tags.md

Add a new topology call to quickly get the available tag/values present in daily topology items. The goal of the call is to present a quick list with all distinct tags and their associated values present in both endpoint and group topology items
The call signature is the following:
`/api/v2/topology/tags`
The sample response is the following:
```
{
"status": {
"message": "application/json",
"code": "200"
},
"data": {
{
"name": "endpoints",
"values": [
{
"name": "tag1",
"values": ["value1", "value2", "value3"]
},
{
"name": "tag2",
"values": ["value1", "value2"]
}
]
},
{
"name": "groups",
"values": [
{
"name": "tag3",
"values": ["value1", "value2", "value3"]
},
{
"name": "tag4",
"values": ["value1"]
}
]
},
}
}
```

ARGO-2724 Introduce topology tags/values method

---

app/topology/model.go
app/topology/topology_test.go
website/docs/topology_endpoints.md
website/docs/topology_groups.md

Add notification information (contacts and notifications enabled/disabled) per topology item: groups and endpoints

ARGO-2885 Add notification information to topology items

---

app/reports/reportsModel.go
app/reports/reports_test.go
website/docs/reports.md

Till now weight datasets were not directly referenced by a report. Instead per report the connector generated an appropriate weight dataset carrying the same name as the report intended to be used. On most tenant cases the same weight dataset was generated multiple times for each report which is inefficient. Instead it would be more robust for each report to optionally reference a weight dataset to be used. So for example for a tenant with 6 reports all of which use the same weights dataset we need 6 references to a single item and the weights dataset stored only once per day in the database.
Reports already have a convenient list of profiles reference to reference profiles to be used along with the report computation such as metrics, operations, aggreagation and thresholds ones. We can …

ARGO-2880 Connect specific weight datasets to each report

---

app/trends/controller.go
app/trends/model.go
app/trends/routing.go
app/trends/trends_test.go
app/trends/view.go
doc/swagger/swagger.yaml
routing/routes.go
scripts/mongodb/populate_default_roles.js
website/docs/trends.md
website/sidebars.js

ARGO-3075 Display endpoint flapping trends
ARGO-3076 Display service flapping trends
ARGO-3077 Display group flapping trends
Provide four calls to display flapping trends for metrics, endpoints, services and endpoint groups
ℹ️ flapping items are the ones that change state too frequently. This causes a lot of alarms and notifications. Flapping usually is the result of wrong configuration. 
Argo-web-api provides the following calls to quickly view the top flapping metrics, endpoints, services and groups:
- *metrics*: `/api/v2/trends/{report_name}/flapping/metrics?date={date}`
- *endpoints*: `/api/v2/trends/{report_name}/flapping/endpoints?date={date}`
- *services*: `/api/v2/trends/{report_name}/flapping/services?date={date}`
- *groups*: …

ARGO-3074 Display metric flapping trends

---

app/trends/controller.go
app/trends/trends_test.go
doc/swagger/swagger.yaml
website/docs/trends.md

Goal:
====
Till now we served trends flapping results per specific date by using the url Query parameter `?date=YYYY-MM-DD`.
We need to be able to also show top flapping results over a range of dates (start --> end)
Implementation:
============
Introduce two additional optional url Parameters: `start_date=YYYY-MM-DD` and `end_date=YYYY-MM-DD`. If `?date=YYYY-MM-DD` is defined as previously then we serve results for the range of a single day (e.g. 2021-06-25 --> 2021-06-25). If date is omitted and instead start_date and end_date are used we display aggregated results over the defined period. 
*Extras:* We also added a `?top=INTEGER` query parameter to be able to display a limit of top results.
Mongodb queries were modified to complex aggregations that match over a range of dates and then …

ARGO-3186 Show flapping trends over range of time

---

app/trends/controller.go
app/trends/model.go
app/trends/trends_test.go
app/trends/view.go
doc/swagger/swagger.yaml
website/docs/trends.md

When exploring flapping trends:
- `/api/v1/trends/{report_name}/flapping/metrics`
- `/api/v1/trends/{report_name}/flapping/endpoints`
- `/api/v1/trends/{report_name}/flapping/services`
- `/api/v1/trends/{report_name}/flapping/groups`
and the start_date & end_date range is used ... Give the ability to aggregate results per month 
Introduce `?granularity=monthly` parameter which is optional but when used aggregates results per month. Lets see it in example:
👉  Get service results for period of 2 months 2021-04-01 ➡️ 2021-05-31 without monthly aggregation:
`HTTP GET /api/v1/trends/{report_name}/flapping/services?start_date=2021-04-01&end_date=2021-05-31`
Response:
```json
"status": {
"message": "Success",
"code": "200"
},
"data": [
{
"endpoint_group": "SITE-A",
"service": "service-A", …
```

ARGO-3193 Add monthly granularity option over flapping trends

---

app/trends/controller.go
app/trends/model.go
app/trends/routing.go
app/trends/trends_test.go
app/trends/view.go
doc/swagger/swagger.yaml
website/docs/trends.md

Introduce a new category of trends: status metrics
Status metrics displays top service endpoint metrics by status type (CRITICAL, WARNING etc) over a range of time
The new api call has the following signature path
`HTTP GET /api/v1/trends{report_name}/status/metrics`
and uses the following parameters:
- `?start_date=YYYY-MM-DD` & `end_date=YYYY-MM-DD` for ranges
- `?date=YYYY-MM-DD` for singe day results
- `?granularity=monthly` for monthly aggregation of ranged results
- `?top=N` for limiting results on top N items
Examples and response format 
👉  Get status metrics results for period of 2 months 2021-04-01 ➡️ 2021-05-31 without monthly aggregation:
`HTTP GET /api/v1/trends/{report_name}/status/metrics?start_date=2021-04-01&end_date=2021-05-31`
Response:
```json
{
"status": {
"message": …
```

ARGO-3197 Display status trend results for metrics

---

app/topology/controller.go
app/topology/topology_test.go
website/docs/reports.md

Allow filtering with multiple values when we have tags that represent comma separated lists. Example of one such tag is scope. 
Usually scope tags have the following pattern
```
{
"scope" : "value1, value2, value3, value4"
}
```
We need to apply a report filter to such tags using a comma separated pattern
For example:
Filter = `{ "scope" : "value4, value3" }` 
show only elements that have value4 or value3 in their scope tags (or both) 
The current report filters:
- `argo.endpoint.filter.tags`
- `argo.group.filter.tags`
Treat endpoint and group tags as single value strings which can be filtered using regular expressions
We introduce two new report filters 
- `argo.endpoint.filter.tags.array`
-  `argo.group.filter.tags.array`
Which can accept a comma separated list of possible values and …

ARGO-3161 Fix issue with multiple values filtering in tags

---

app/topology/controller.go
app/topology/topology_test.go

Issue 
====
When listed endpoint groups filtered by report there were unwanted items in the list (edge cases)
Cause
=====
Each report has a topology hierarchy section which lists what kind of structure the report computes eg:
```json
{
"topology_schema": {
"group": {
"type": "PROJECT",
"group": {
"type": "SERVICEGROUPS"
}
}
}
}
```
When listed filtered groups by report the topology schema was taken into account and provided specific extensions to the datastore query (eg. filter groups by type: "PROJECT")
In the case of listing filtered endpoints by report the specific extensions on datastore queries so as to filter by specific group type were not added correctly
Implementation
============
In request handler method ListEndpointsByReport apply correctly the group and endpoint type filters …

ARGO-3225 Fix endpoint group type filtering by report

---

app/downtimes/controller.go
app/downtimes/downtimes_test.go

Fix downtime response consistency when no declared downtimes are found... 
Instead of returning just
```
{
"data" : [ ] 
}
```
We need to return 
```
{
"data" : [ 
{
"date": "YYYY-MM-DD"
"endpoints": [ ]
}
]
}
```

ARGO-3269 Fix empty downtime response

---

argo-web-api.spec
version/version.go

v.1.10.0 - 2021-09-02
**Added**:
- ARGO-3197 Display status trend results for metrics
- ARGO-3193 Add monthly granularity option over flapping trends
- ARGO-3186 Show flapping trends over range of time
- ARGO-3077 Display group flapping trends
- ARGO-3076 Display service flapping trends
- ARGO-3075 Display endpoint flapping trends 
- ARGO-3074 Display metric flapping trends 
- ARGO-2885 Add notification information to topology items
- ARGO-2724 Introduce topology tags/values method 
**Fixed**:
- ARGO-3269 Fix empty downtime response
- ARGO-3241 close mongodb sessions in recomputation handlers
- ARGO-3225 Fix endpoint group type filtering by report
- ARGO-3161 Fix issue with multiple values filtering in tags
**Changed**:
- ARGO-3265 Return exact date downtime instead of close to date
- …

version 1.10.0

---

app/trends/controller.go
app/trends/model.go
app/trends/routing.go
app/trends/trends_test.go
app/trends/view.go
doc/swagger/swagger.yaml
scripts/mongodb/populate_default_roles.js
website/docs/trends.md

Introduce a new category of trends: status metrics
Status endpoint trends displays top service endpoints by status type (CRITICAL, WARNING etc)  duration over a range of time
The new api call has the following signature path
`HTTP GET /api/v1/trends{report_name}/status/endpoints`
and uses the following parameters:
- `?start_date=YYYY-MM-DD` & `end_date=YYYY-MM-DD` for ranges
- `?date=YYYY-MM-DD` for singe day results
- `?granularity=monthly` for monthly aggregation of ranged results
- `?top=N` for limiting results on top N items
Examples and response format 
👉  Get status endpoint results for period of 2 months 2021-04-01 ➡️ 2021-05-31 without monthly aggregation:
`HTTP GET /api/v1/trends/{report_name}/status/endpoints?start_date=2021-04-01&end_date=2021-05-31`
Response:
```json
{ …
```

ARGO-3279 Create Endpoint status trends view

---

app/trends/controller.go
app/trends/model.go
app/trends/routing.go
app/trends/trends_test.go
app/trends/view.go
doc/swagger/swagger.yaml
scripts/mongodb/populate_default_roles.js
website/docs/trends.md

Introduce a new category of trends: status services
Status service trends displays top  services by status type (CRITICAL, WARNING etc)  duration over a range of time
The new api call has the following signature path
`HTTP GET /api/v1/trends{report_name}/status/services`
and uses the following parameters:
- `?start_date=YYYY-MM-DD` & `end_date=YYYY-MM-DD` for ranges
- `?date=YYYY-MM-DD` for singe day results
- `?granularity=monthly` for monthly aggregation of ranged results
- `?top=N` for limiting results on top N items
Examples and response format 
👉  Get status service results for period of 2 months 2021-04-01 ➡️ 2021-05-31 without monthly aggregation:
`HTTP GET /api/v1/trends/{report_name}/status/services?start_date=2021-04-01&end_date=2021-05-31`
Response:
```json
{
"status": { …
```

ARGO-3280 create status trends view for services

---

app/trends/controller.go
app/trends/model.go
app/trends/routing.go
app/trends/trends_test.go
app/trends/view.go
doc/swagger/swagger.yaml
scripts/mongodb/populate_default_roles.js
website/docs/trends.md

Introduce a new category of trends: status endpoint groups
Status service trends displays top endpoint groups by status type (CRITICAL, WARNING etc)  duration over a range of time
The new api call has the following signature path
`HTTP GET /api/v1/trends{report_name}/status/groups`
and uses the following parameters:
- `?start_date=YYYY-MM-DD` & `end_date=YYYY-MM-DD` for ranges
- `?date=YYYY-MM-DD` for singe day results
- `?granularity=monthly` for monthly aggregation of ranged results
- `?top=N` for limiting results on top N items
Examples and response format 
👉  Get status endpoint groups results for period of 2 months 2021-04-01 ➡️ 2021-05-31 without monthly aggregation:
`HTTP GET /api/v1/trends/{report_name}/status/services?start_date=2021-04-01&end_date=2021-05-31`
Response:
```json
{ …
```

ARGO-3281 create status trends for endpoint groups

---

app/metrics/controller.go
app/metrics/metrics__admin_test.go
app/metrics/metrics_test.go
app/metrics/model.go
app/metrics/routing.go
app/metrics/view.go
doc/swagger/swagger.yaml
respond/wrappers.go
routing/routes.go
scripts/mongodb/populate_default_roles.js
website/docs/metric_results.md
website/docs/metrics.md

superpoem associates metrics with tags for better description. This information doesn't exist yet in the argo-web-api. We must implement an api resource to hold this info as a list of metrics (described by `name` and `tags` fields)
The metric list is common for all tenants
There are two adminstrative calls to view and update the list:
- `PUT` `/api/v2/admin/metrics/` updates the metric list
- `GET` `/api/v2/admin/metrics/` returns the metric list
The metric list is also readable only from each tenants
There are two tenant-scoped calls to view the metric list:
- `PUT` `/api/v2/metrics` returns the whole metric list
- `GET` `/api/v2/metrics/by_report/{report_name}` returns only the metrics relevant to a report
Example response of a metric list:
```json
{
"status": {
"message": "Success", …
```

ARGO-3423 Add list of metric to tags mappings

---

app/topology/controller.go
app/topology/topology_test.go
website/docs/reports.md
website/docs/topology_endpoints.md
website/docs/topology_groups.md

Be able to easily exclude topology items in filters
Idea:
When using the `GET` `/topology/groups` and `/topology/endpoints` calls the user can specify filters in the url query string such as:
- `/topology/groups?type=SERVICEGROUP`
- `/topology/endpoints?service=SERVICE_A`
The user can easilyexclude something that has attribute=value1 by using `~` as an exclude/negative operator in the beginning of the value, for example: attribute=~value1 
_(note: `!` is a reserved character and may cause issues in url query strings so `~` was chosen instead)_
So the user can perform queries with exclusion such as:
- `/topology/groups?type=~SITES` (exclude groups that are of the type **SITES**)
- `/topology/endpoints?service=~WEBSERVER` (exclude endpoints that run the **WEBSERVER** service)
*wildcard …

ARGO-3377 Add negative operator in topology filtering

---

app/statusFlatMetrics/statusFlatMetrics_test.go
app/statusFlatMetrics/view.go
app/statusMetrics/statusMetrics_test.go
app/statusMetrics/view.go

"threshold_rule_applied" field erroneously showed the "actual_data" field value instead of the actual rule applied

ARGO-3452 Fix threshold rule applied field value in status metrics

---

app/statusEndpointGroups/controller.go
app/statusEndpointGroups/model.go
app/statusEndpointGroups/statusEndpointGroups_test.go
app/statusEndpointGroups/view.go
app/statusEndpoints/controller.go
app/statusEndpoints/model.go
app/statusEndpoints/statusEndpoints_test.go
app/statusEndpoints/view.go
app/statusFlatEndpoints/controller.go
app/statusFlatEndpoints/model.go
app/statusFlatEndpoints/statusFlatEndpoints_test.go
app/statusFlatEndpoints/view.go
app/statusServices/controller.go
app/statusServices/model.go
app/statusServices/statusServices_test.go
app/statusServices/view.go
doc/swagger/swagger.yaml
website/docs/status.md

Display info if a status has been affected by a threshold rules on top level results:
- endpoints
- services
- groups
By using the url parameter `view=details` the argo-web-api will enrich the status timeline results with additional information in case a threshold rule has been applied to the results. For example:
```json
{
"groups": [
{
"name": "SITE-A",
"type": "SITES",
"services": [
{
"name": "SERVICE-A",
"type": "service",
"statuses": [
{
"timestamp": "2015-04-30T23:59:00Z",
"value": "OK"
},
{
"timestamp": "2015-05-01T01:00:00Z",
"value": "CRITICAL",
"affected_by_threshold_rule": true
},
{
"timestamp": "2015-05-01T02:00:00Z",
"value": "OK"
},
{
"timestamp": "2015-05-01T23:59:59Z",
"value": "OK"
}
]
}
]
}
]
}
```

ARGO-3408 Serve threshold flag trough web-api

---

app/reports/reportsController.go
app/reports/reportsModel.go
app/reports/reports_test.go
doc/swagger/swagger.yaml
website/docs/reports.md

Add additional information on the report body stating what should and is being computed (ar, status and specifically which trends)
The additional information of what each report computes is specified in the body of the report with the special field `computations`. The json is presented below: 
```json
{
"computations": {
"ar": true,
"status": true,
"trends": [
"flapping",
"status",
"tags"
]
}
}
```
If the user wants ar computations to be executed specified `"ar": true` - same for status (`"status": true`)
Also in the "trends" array user can specify specific trends that need to be computed

ARGO-3874 Add info on the report about what is computed (ar,status,trends)

---

argo-web-api.spec
version/version.go
website/package.json

- Bump version to v.1.12.0 to prepare for release
- Minor fix in documentation config: correct project name

Bump to v.1.12.0

---

app/downtimes/controller.go
app/downtimes/downtimes_test.go
app/downtimes/model.go
doc/swagger/swagger.yaml
website/docs/downtimes.md

ARGO-3926 Add description to downtimes
Add optional fields of `description`, `classification` and `severity` to downtimes. Old downtimes will display correctly without those fields. Also give the ability when listing downtimes to filter by classification and severity
👉  Ability to list downtimes by classification and severity example:
`HTTP GET /api/v2/downtimes?date=2022-05-11&classification=scheduled&severity=outage`
Response:
```json
{
"status": {
"message": "Success",
"code": "200"
},
"data": [
{
"date": "2022-05-11",
"endpoints": [
{
"hostname": "host-A",
"service": "service-A",
"start_time": "2022-05-11T04:00:33Z",
"end_time": "2022-05-11T15:33:00Z",
"severity": "outage",
"classification": "scheduled"
},
{
"hostname": "host-B",
"service": "service-B",
"start_time": …
```

ARGO-3928 organise downtimes by severity and classification

---

scripts/mongodb/populate_default_roles.js
v3/status/handlers.go
v3/status/models.go
v3/status/queries.go
v3/status/routing.go
v3/status/status_test.go
v3/status/views.go
website/docs/apiv3/v3status.md
website/static/openapi/argo-web-api.yml

Give the ability to retrieve the latest status results for an endpoint by providing it's resource-id 
Create a new api method to retrieve status results for a *specific* endpoint
👉 `HTTP GET /api/v3/status/{report_name}/id/{resource_id}`
or
👉 `HTTP GET /api/v3/status/{report_name}/id/{resource_id}?view=details&start_time={value}&end_time={value}`
For example:
`HTTP GET /api/v3/status/Critical/id/simple-queue`
```json
{
"id": "simple-queue",
"endpoints": [
{
"hostname": "queue01.example.com",
"service": "compute.queue",
"group": "Infra-01",
"info": {
"URL": "http://submit.queue01.example.com"
},
"statuses": [
{
"timestamp": "2022-10-12T13:25:26Z",
"value": "OK"
}
]
}
]
}
```
The method can also return a full timeline of status results when `view=details` url parameter is used. Also user …

ARGO-4026 api v3 call to get status results by resource id

---

v3/ar/ar_test.go
v3/ar/handlers.go
v3/ar/models.go
v3/ar/routing.go
v3/ar/views.go
website/docs/apiv3/v3results.md

Give the ability to retrieve the latest ar results for an endpoint by providing it's resource-id 
Create a new api method to retrieve status results for a *specific* endpoint
👉 `HTTP GET /api/v3/results/{report_name}/id/{resource_id}`
or
👉 `HTTP GET /api/v3/results/{report_name}/id/{resource_id}&start_time={value}&end_time={value}`
For example:
`HTTP GET /api/v3/results/Critical/id/simple-queue`

Implement api/v3 call to serve endpoint ar results by resource id

---

v3/ar/ar_test.go
v3/ar/handlers.go
v3/ar/models.go
v3/ar/queries.go
v3/ar/views.go
website/docs/apiv3/v3results.md
website/static/openapi/argo-web-api.yml

Fix v3 ar results by resource-id call

---

v3/ar/ar_test.go
v3/ar/handlers.go
v3/ar/validations.go

ARGO-4087 Fix date validation in api/v3 A/R calls

---

app/results/Controller.go
app/results/Model.go
app/results/View.go
app/results/endpoint_test.go
app/results/endpointgroup_test.go
app/results/queries.go
app/results/serviceflavor_test.go
app/results/supergroup_test.go
doc/v2/docs/errors.md
doc/v2/docs/validations.md
respond/validators.go
v3/ar/ar_test.go
v3/ar/handlers.go
v3/ar/models.go
v3/ar/validations.go
v3/ar/views.go
website/docs/apiv3/v3results.md
website/docs/results/results.md
website/docs/validation_and_errors/errors.md
website/docs/validation_and_errors/validations.md
website/static/openapi/argo-web-api.yml

Unit now the user can specify a period with start_time and end_time and get results in two ways
- by date (daily)
- by month (monthly)
We provide a third granularity option with `custom` that allows the user to get a/r results for the whole custom period that he has defined
We need to provide another version of the `Monthly` or `Daily` queries as `Custom` such as
- EndpointCustom
- SupergroupCustom
- ServiceCustom
- EndpointCustom 
aggregations
Each such aggregation will not group items by date (day/month) so as to be able to aggregate over the whole set of daily days that the user has specified

ARGO-3360 Support custom period in a/r results

---

argo-web-api.spec
version/version.go

**Added:**
- ARGO-4089 support OPTIONS for api v3 calls using resource-ids
- ARGO-4048 add additional tags field list of service types
- ARGO-4078 Implement api/v3 call to serve endpoint ar results by resource id
- ARGO-4026 api v3 call to get status results by resource id
**Changed**
- ARGO-3960 Update to docusaurus v.2.0. Add search plugin. Spellcheck docs
**Fixed**
- ARGO-4087 Fix date validation in api/v3 A/R calls
- ARGO-4084 Fix v3 ar results by resource-id call

Bump version to v1.13.0

---

app/issues/controller.go
app/issues/issues_test.go
app/issues/model.go
app/issues/routing.go
app/issues/view.go
scripts/mongodb/populate_default_roles.js
website/docs/results/issues.md
website/static/openapi/argo-web-api.yml

For a specific group e.g. `SITE-A` list all problematic metrics for a day
Add a new endpoint under `/issues` path
`/api/v2/issues/{report_name}/groups/{group_name}/metrics?date=YYYY-MM-DD&filter={status}`
- `group_name` the name of the group (e.g. SITE-A)
- `filter` = optional  - show only metrics with CRITICAL, WARNING,MISSING etc. status
Response is in the following form:
```json
{
"status": {
"message": "Success",
"code": "200"
},
"data": [
{
"service": "web_portal",
"hostname": "web01.example.gr",
"metric": "http_check",
"status": "WARNING",
"info": {
"Url": "http://example.foo/path/to/service"
}
},
{
"service": "web_portal",
"hostname": "web02.example.gr",
"metric": "http_check",
"status": "CRITICAL",
"info": {
"Url": "http://example2.foo/path/to/service"
}
}
]
}
```

ARGO-4096 Daily issues per group

---

.github/dependabot.yml

Configure dependabot updates against `devel` branch for both go deps and docusaurus deps (npm)

ARGO-4115 Configure dependabot updates

---

app/topology/model.go
app/topology/topology_test.go
website/docs/topology/topology_service_types.md
website/static/openapi/argo-web-api.yml

Add an extra field named `"title"` in the service type resource. The title will contain a more user-friendly and human readable name for the service it self 
example
```json
{
"name": "namespace.obj.datastore"
"title": "Object Datatastore Service"
"description": "A Service type representing instances of object datastores"
"tags" : [ "datastore", "objects" ]
} 
```

ARGO-4185 Add title field to service types

---

app/statusEndpoints/controller.go
app/statusEndpoints/routing.go
app/statusEndpoints/statusEndpoints_test.go
website/docs/results/status.md
website/static/openapi/argo-web-api.yml

Till now in order to view status timelines for endpoints in a group a user had to follow the path selecting a specific service type: 
```
/v2/status/REPORT-A/SERVICEGROUPS(or SITES)/GROUP-A/services/SERVICE-TYPE-A/endpoints
```
User now can quickly retrieve status timelines for all endpoints included in a group (without having to specify a service-type):
```
/v2/status/REPORT-A/SERVICEGROUPS(or SITES)/GROUP-A/endpoints
```

ARGO-4196 Get status timelines for all endpoints in a specific group

---

app/metricResult/controller.go
app/metricResult/metric_test.go
app/metricResult/model.go
app/metricResult/view.go
website/docs/results/metric_results.md
website/static/openapi/argo-web-api.yml

Add optional `service=` url parameter as a filter in requests that return low level metric results
- Add filter structure in controllers
- Add filter logic in queries
- Condense metric result rendering view in one function for both controllers
- Update unit tests with relevant scenarios
- Update docs

ARGO-4206 Add filter by service type when requesting metric results

---

.github/dependabot.yml
website/package-lock.json

- Bump json5 dep:`2.2.1` → `2.2.3` ref: https://github.com/ARGOeu/argo-web-api/pull/475
- Bump ua-parser-js:  `0.7.31` → `0.7.33` ref: https://github.com/ARGOeu/argo-web-api/pull/480
- Fix dependabot yml: `develop` → `devel` branch for npm checks

Bump docusaurus deps: json5, ua-parser-js. Branch Fix in dependabot yml

---

argo-web-api.spec
version/version.go

**Added:**
- ARGO-4206 Add filter by service type when requesting metric results 
**Fixed:**
- ARGO-4226 In recomputations fix support for exclude monitoring source

Version 1.13.2

---

app/topology/controller.go
app/topology/model.go
app/topology/topology_test.go
website/docs/topology/topology_endpoints.md
website/docs/topology/topology_groups.md
website/static/openapi/argo-web-api.yml

When using a "combined" tenant give the ability to request the list of all endpoint topology items in the tenants included in the combined feed
Extend the `/topology/endpoints` call with an extra `mode=combined` parameter such as
`/api/v2/topology/endpoints?mode=combined` which returns a list with all group topology items found in the tenants included in the combined data feeds. Items retrieved from included tenants receive an extra field `tenant` to identify their source
Do the same for `/topology/endpoints/by_report/{report_name}?mode=combined`

ARGO-4207 provide automatically combined endpoints in topology of combined tenants

---

app/topology/controller.go
app/topology/model.go
app/topology/topology_test.go
website/docs/topology/topology_groups.md
website/static/openapi/argo-web-api.yml

When using a "combined" tenant give the ability to request the list of all group topology items in the tenants included in the combined feed
Extend the `/topology/groups` call with an extra `mode=combined` parameter such as
`/api/v2/topology/groups?mode=combined` which returns a list with all group topology items found in the tenants included in the combined data feeds. Items retrieved from included tenants receive an extra field `tenant` to identify their source
Do the same for `/topology/groups/by_report/{report_name}?mode=combined`

ARGO-4208 Provide automatically combined groups in topology of combined tenants

---

Jenkinsfile
app/metricResult/controller.go
app/metricResult/metric_test.go
app/metricResult/model.go
app/metricResult/view.go
website/docs/results/metric_results.md
website/static/openapi/argo-web-api.yml

Fix regression by re-adding the following:
Add optional `service=` url parameter as a filter in requests that return low level metric results
- Add filter structure in controllers
- Add filter logic in queries
- Condense metric result rendering view in one function for both controllers
- Update unit tests with relevant scenarios
- Update docs

Fix metric-details filter by service regression

---

app/recomputations2/Controller.go
app/recomputations2/Model.go
app/recomputations2/recomputation_test.go

_⚠️ This PR is opened against feature branch go1.22-mongo6.0 which is not merged yet in devel. After testing this implementation we can proceed with finally merging go1.22-mongo6.0 feature branch in the devel branch_
Argo was required to support a new kind of recomputations named applied statuses recomputations where a requestor can ask to apply specific statuses over a period of time on timelines of groups, services, endpoints and/or metrics. This new kind of recomputations is supported by adding an extra field "applied_status_changes" so the recomputation body becomes like the following example:
```json
{
"id": "56db4f1a-f331-46ca-b0fd-4555b4aa1cfc",
"requester_name": "requester",
"requester_email": "request@request.gr",
"reason": "testing_compute_engine",
"start_time": …
```

ARGO-5002 Support applied status recomputations

---

website/docs/results/recomputations.md

This pr introduces changes to the description of recomputaton requests on API . 
Added the body structure of the POST recomputations to describe how to define the different recomputation types. 
Removed the excluded metrics and monitoring sources description as this part is added to the documentaton of Argo Monitoriring Service along with the rest types of recomputations. We try to keep here only the description on the api structure and not concepts

add documentation for POST recomputations

---

consistency/consistency_test.go
consistency/handlers.go
consistency/models.go
consistency/views.go
health/handlers.go
health/health_test.go
health/models.go
health/views.go
routing/routes.go
scripts/consistency/config.yml
scripts/consistency/consistency-check.py
scripts/consistency/requirements.txt
scripts/mongodb/populate_default_roles.js
website/docs/consistency.md
website/docs/health.md
website/static/openapi/argo-web-api.yml

Give to the end user a health endpoint to get informed about the health status of argo web api 
```
GET /api/v2/health 
````
```json
{
"status" : "OK",
"timestamp": "2025-05-10T00:05:00Z",
"message": "No flapping endpoints"
}
```
Give the ability to have a consistency check endpoint to get quickly information about the status of the consistency of data in argo-web-api. The response is something like this:
```
GET /api/v2/consistency
```
```json
{
"status" : "OK",
"timestamp": "2025-05-10T00:05:00Z",
"message": "Flapping items under 50% (3 in 100)"
}
```
An automated check running at intervals (outside the api) check the api and various tenants/reports for issues in trends and posts the consistency results using the following endpoint
```
POST /api/v2/consistency/auto-check
```
```json
{ …
```

ARGO-5073 Add support for consistency check
